// Code generated by lark suite oapi sdk gen
/*
 * MIT License
 *
 * Copyright (c) 2022 Lark Technologies Pte. Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice, shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.lark.oapi.service.apaas.v1.model;

import com.lark.oapi.core.response.EmptyData;
import com.lark.oapi.service.apaas.v1.enums.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.SerializedName;
import com.lark.oapi.core.annotation.Body;
import com.lark.oapi.core.annotation.Path;
import com.lark.oapi.core.annotation.Query;

import java.io.ByteArrayOutputStream;
import java.io.FileOutputStream;
import java.io.IOException;

import com.lark.oapi.core.utils.Strings;
import com.lark.oapi.core.response.BaseResponse;

public class ConnectorInstanceDefinition {
    /**
     * 连接器源类型
     * <p> 示例值：connector
     */
    @SerializedName("connector_source_type")
    private String connectorSourceType;
    /**
     * 连接器APIName
     * <p> 示例值：test_connector
     */
    @SerializedName("connector_api_name")
    private String connectorApiName;
    /**
     * 连接器Action APIName
     * <p> 示例值：test_action
     */
    @SerializedName("action_api_name")
    private String actionApiName;
    /**
     * 连接APIName
     * <p> 示例值：test_connection
     */
    @SerializedName("connection_api_name")
    private String connectionApiName;
    /**
     * 输入参数
     * <p> 示例值：\{\}
     */
    @SerializedName("input_data")
    private String inputData;
    /**
     * 输出数据schema
     * <p> 示例值：\{\}
     */
    @SerializedName("output_data_schema")
    private String outputDataSchema;

    // builder 开始
    public ConnectorInstanceDefinition() {
    }

    public ConnectorInstanceDefinition(Builder builder) {
        /**
         * 连接器源类型
         * <p> 示例值：connector
         */
        this.connectorSourceType = builder.connectorSourceType;
        /**
         * 连接器APIName
         * <p> 示例值：test_connector
         */
        this.connectorApiName = builder.connectorApiName;
        /**
         * 连接器Action APIName
         * <p> 示例值：test_action
         */
        this.actionApiName = builder.actionApiName;
        /**
         * 连接APIName
         * <p> 示例值：test_connection
         */
        this.connectionApiName = builder.connectionApiName;
        /**
         * 输入参数
         * <p> 示例值：\{\}
         */
        this.inputData = builder.inputData;
        /**
         * 输出数据schema
         * <p> 示例值：\{\}
         */
        this.outputDataSchema = builder.outputDataSchema;
    }

    public static Builder newBuilder() {
        return new Builder();
    }

    public String getConnectorSourceType() {
        return this.connectorSourceType;
    }

    public void setConnectorSourceType(String connectorSourceType) {
        this.connectorSourceType = connectorSourceType;
    }

    public String getConnectorApiName() {
        return this.connectorApiName;
    }

    public void setConnectorApiName(String connectorApiName) {
        this.connectorApiName = connectorApiName;
    }

    public String getActionApiName() {
        return this.actionApiName;
    }

    public void setActionApiName(String actionApiName) {
        this.actionApiName = actionApiName;
    }

    public String getConnectionApiName() {
        return this.connectionApiName;
    }

    public void setConnectionApiName(String connectionApiName) {
        this.connectionApiName = connectionApiName;
    }

    public String getInputData() {
        return this.inputData;
    }

    public void setInputData(String inputData) {
        this.inputData = inputData;
    }

    public String getOutputDataSchema() {
        return this.outputDataSchema;
    }

    public void setOutputDataSchema(String outputDataSchema) {
        this.outputDataSchema = outputDataSchema;
    }

    public static class Builder {
        /**
         * 连接器源类型
         * <p> 示例值：connector
         */
        private String connectorSourceType;
        /**
         * 连接器APIName
         * <p> 示例值：test_connector
         */
        private String connectorApiName;
        /**
         * 连接器Action APIName
         * <p> 示例值：test_action
         */
        private String actionApiName;
        /**
         * 连接APIName
         * <p> 示例值：test_connection
         */
        private String connectionApiName;
        /**
         * 输入参数
         * <p> 示例值：\{\}
         */
        private String inputData;
        /**
         * 输出数据schema
         * <p> 示例值：\{\}
         */
        private String outputDataSchema;

        /**
         * 连接器源类型
         * <p> 示例值：connector
         *
         * @param connectorSourceType
         * @return
         */
        public Builder connectorSourceType(String connectorSourceType) {
            this.connectorSourceType = connectorSourceType;
            return this;
        }


        /**
         * 连接器APIName
         * <p> 示例值：test_connector
         *
         * @param connectorApiName
         * @return
         */
        public Builder connectorApiName(String connectorApiName) {
            this.connectorApiName = connectorApiName;
            return this;
        }


        /**
         * 连接器Action APIName
         * <p> 示例值：test_action
         *
         * @param actionApiName
         * @return
         */
        public Builder actionApiName(String actionApiName) {
            this.actionApiName = actionApiName;
            return this;
        }


        /**
         * 连接APIName
         * <p> 示例值：test_connection
         *
         * @param connectionApiName
         * @return
         */
        public Builder connectionApiName(String connectionApiName) {
            this.connectionApiName = connectionApiName;
            return this;
        }


        /**
         * 输入参数
         * <p> 示例值：\{\}
         *
         * @param inputData
         * @return
         */
        public Builder inputData(String inputData) {
            this.inputData = inputData;
            return this;
        }


        /**
         * 输出数据schema
         * <p> 示例值：\{\}
         *
         * @param outputDataSchema
         * @return
         */
        public Builder outputDataSchema(String outputDataSchema) {
            this.outputDataSchema = outputDataSchema;
            return this;
        }


        public ConnectorInstanceDefinition build() {
            return new ConnectorInstanceDefinition(this);
        }
    }
}
