// Code generated by lark suite oapi sdk gen
/*
 * MIT License
 *
 * Copyright (c) 2022 Lark Technologies Pte. Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice, shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.lark.oapi.service.apaas.v1.model;

import com.google.gson.annotations.SerializedName;
import com.lark.oapi.service.apaas.v1.enums.*;

public class FieldPermissionConfigV2 {
  /**
   * 字段权限配置模式
   *
   * <p>示例值：all
   */
  @SerializedName("field_config_mode")
  private String fieldConfigMode;

  /**
   * 自定义字段配置
   *
   * <p>示例值：
   */
  @SerializedName("custom_field_permissions")
  private FieldPermissionV2[] customFieldPermissions;

  public String getFieldConfigMode() {
    return this.fieldConfigMode;
  }

  public void setFieldConfigMode(String fieldConfigMode) {
    this.fieldConfigMode = fieldConfigMode;
  }

  public FieldPermissionV2[] getCustomFieldPermissions() {
    return this.customFieldPermissions;
  }

  public void setCustomFieldPermissions(FieldPermissionV2[] customFieldPermissions) {
    this.customFieldPermissions = customFieldPermissions;
  }

  // builder 开始
  public FieldPermissionConfigV2() {}

  public FieldPermissionConfigV2(Builder builder) {
    /**
     * 字段权限配置模式
     *
     * <p>示例值：all
     */
    this.fieldConfigMode = builder.fieldConfigMode;
    /**
     * 自定义字段配置
     *
     * <p>示例值：
     */
    this.customFieldPermissions = builder.customFieldPermissions;
  }

  public static class Builder {
    /**
     * 字段权限配置模式
     *
     * <p>示例值：all
     */
    private String fieldConfigMode;

    /**
     * 自定义字段配置
     *
     * <p>示例值：
     */
    private FieldPermissionV2[] customFieldPermissions;

    /**
     * 字段权限配置模式
     *
     * <p>示例值：all
     *
     * @param fieldConfigMode
     * @return
     */
    public Builder fieldConfigMode(String fieldConfigMode) {
      this.fieldConfigMode = fieldConfigMode;
      return this;
    }

    /**
     * 字段权限配置模式
     *
     * <p>示例值：all
     *
     * @param fieldConfigMode {@link
     *     com.lark.oapi.service.apaas.v1.enums.FieldPermissionConfigV2FieldConfigModeEnum}
     * @return
     */
    public Builder fieldConfigMode(
        com.lark.oapi.service.apaas.v1.enums.FieldPermissionConfigV2FieldConfigModeEnum
            fieldConfigMode) {
      this.fieldConfigMode = fieldConfigMode.getValue();
      return this;
    }

    /**
     * 自定义字段配置
     *
     * <p>示例值：
     *
     * @param customFieldPermissions
     * @return
     */
    public Builder customFieldPermissions(FieldPermissionV2[] customFieldPermissions) {
      this.customFieldPermissions = customFieldPermissions;
      return this;
    }

    public FieldPermissionConfigV2 build() {
      return new FieldPermissionConfigV2(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
