// Code generated by lark suite oapi sdk gen
package com.lark.oapi.service.application.v6.enums;

// 生成枚举值
public enum ChatTypeEnum {
  PRIVATE("private"),
  GROUP("group"),
  ;
  private String value;

  ChatTypeEnum(String value) {
    this.value = value;
  }

  public String getValue() {
    return this.value;
  }
}