// Code generated by lark suite oapi sdk gen
package com.lark.oapi.service.bitable.v1.model;

import com.google.gson.annotations.SerializedName;
import com.lark.oapi.core.response.BaseResponse;

public class DeleteAppTableRecordResp extends BaseResponse {

  @SerializedName("data")
  private DeleteAppTableRecordDTO body;

  public DeleteAppTableRecordDTO getDeleteAppTableRecordDTO() {
    return this.body;
  }

  public void setDeleteAppTableRecordDTO(DeleteAppTableRecordDTO body) {
    this.body = body;
  }
}
