// Code generated by lark suite oapi sdk gen
package com.lark.oapi.service.bitable.v1.model;

import com.google.gson.annotations.SerializedName;
import com.lark.oapi.core.response.BaseResponse;

public class UpdateAppTableFieldResp extends BaseResponse {

  @SerializedName("data")
  private UpdateAppTableFieldDTO body;

  public UpdateAppTableFieldDTO getUpdateAppTableFieldDTO() {
    return this.body;
  }

  public void setUpdateAppTableFieldDTO(UpdateAppTableFieldDTO body) {
    this.body = body;
  }
}
