// Code generated by lark suite oapi sdk gen
package com.lark.oapi.service.bitable.v1.model;

import com.google.gson.annotations.SerializedName;

public class UpdateAppRoleDTO {

  @SerializedName("role")
  private AppRole role;

  public AppRole getRole() {
    return this.role;
  }

  public void setRole(AppRole role) {
    this.role = role;
  }

}
