// Code generated by lark suite oapi sdk gen
/*
 * MIT License
 *
 * Copyright (c) 2022 Lark Technologies Pte. Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice, shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.lark.oapi.service.spark.v1.resource;

import com.lark.oapi.core.Config;
import com.lark.oapi.core.Transport;
import com.lark.oapi.core.request.RequestOptions;
import com.lark.oapi.core.response.RawResponse;
import com.lark.oapi.core.token.AccessTokenType;
import com.lark.oapi.core.utils.Jsons;
import com.lark.oapi.core.utils.Sets;
import com.lark.oapi.core.utils.UnmarshalRespUtil;
import com.lark.oapi.service.spark.v1.model.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class AppTable {
  private static final Logger log = LoggerFactory.getLogger(AppTable.class);
  private final Config config;

  public AppTable(Config config) {
    this.config = config;
  }

  /**
   * 批量更新数据表中的记录，批量更新应用下的数据表中的记录，每条记录需包含主键如_id，单次最多500条。
   *
   * <p>官网API文档链接:<a
   * href="https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=batch_update_table_records&project=spark&resource=app.table&version=v1">https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=batch_update_table_records&project=spark&resource=app.table&version=v1</a>
   * ;
   *
   * <p>使用Demo链接: <a
   * href="https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/sparkv1/BatchUpdateTableRecordsAppTableSample.java">https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/sparkv1/BatchUpdateTableRecordsAppTableSample.java</a>
   * ;
   */
  public BatchUpdateTableRecordsAppTableResp batchUpdateTableRecords(
      BatchUpdateTableRecordsAppTableReq req, RequestOptions reqOptions) throws Exception {
    // 请求参数选项
    if (reqOptions == null) {
      reqOptions = new RequestOptions();
    }

    // 发起请求
    RawResponse httpResponse =
        Transport.send(
            config,
            reqOptions,
            "PATCH",
            "/open-apis/spark/v1/apps/:app_id/tables/:table_name/records_batch_update",
            Sets.newHashSet(AccessTokenType.User),
            req);

    // 反序列化
    BatchUpdateTableRecordsAppTableResp resp =
        UnmarshalRespUtil.unmarshalResp(httpResponse, BatchUpdateTableRecordsAppTableResp.class);
    if (resp == null) {
      log.error(
          String.format(
              "%s,callError,req=%s,respHeader=%s,respStatusCode=%s,respBody=%s,",
              "/open-apis/spark/v1/apps/:app_id/tables/:table_name/records_batch_update",
              Jsons.DEFAULT.toJson(req),
              Jsons.DEFAULT.toJson(httpResponse.getHeaders()),
              httpResponse.getStatusCode(),
              new String(httpResponse.getBody(), StandardCharsets.UTF_8)));
      throw new IllegalArgumentException("The result returned by the server is illegal");
    }

    resp.setRawResponse(httpResponse);
    resp.setRequest(req);

    return resp;
  }

  /**
   * 批量更新数据表中的记录，批量更新应用下的数据表中的记录，每条记录需包含主键如_id，单次最多500条。
   *
   * <p>官网API文档链接:<a
   * href="https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=batch_update_table_records&project=spark&resource=app.table&version=v1">https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=batch_update_table_records&project=spark&resource=app.table&version=v1</a>
   * ;
   *
   * <p>使用Demo链接: <a
   * href="https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/sparkv1/BatchUpdateTableRecordsAppTableSample.java">https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/sparkv1/BatchUpdateTableRecordsAppTableSample.java</a>
   * ;
   */
  public BatchUpdateTableRecordsAppTableResp batchUpdateTableRecords(
      BatchUpdateTableRecordsAppTableReq req) throws Exception {
    // 请求参数选项
    RequestOptions reqOptions = new RequestOptions();

    // 发起请求
    RawResponse httpResponse =
        Transport.send(
            config,
            reqOptions,
            "PATCH",
            "/open-apis/spark/v1/apps/:app_id/tables/:table_name/records_batch_update",
            Sets.newHashSet(AccessTokenType.User),
            req);

    // 反序列化
    BatchUpdateTableRecordsAppTableResp resp =
        UnmarshalRespUtil.unmarshalResp(httpResponse, BatchUpdateTableRecordsAppTableResp.class);
    if (resp == null) {
      log.error(
          String.format(
              "%s,callError,req=%s,respHeader=%s,respStatusCode=%s,respBody=%s,",
              "/open-apis/spark/v1/apps/:app_id/tables/:table_name/records_batch_update",
              Jsons.DEFAULT.toJson(req),
              Jsons.DEFAULT.toJson(httpResponse.getHeaders()),
              httpResponse.getStatusCode(),
              new String(httpResponse.getBody(), StandardCharsets.UTF_8)));
      throw new IllegalArgumentException("The result returned by the server is illegal");
    }

    resp.setRawResponse(httpResponse);
    resp.setRequest(req);

    return resp;
  }

  /**
   * 删除数据表中的记录，删除指定应用下数据表中符合filter筛选条件的记录，删除后记录不可恢复。
   *
   * <p>官网API文档链接:<a
   * href="https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=delete_table_records&project=spark&resource=app.table&version=v1">https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=delete_table_records&project=spark&resource=app.table&version=v1</a>
   * ;
   *
   * <p>使用Demo链接: <a
   * href="https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/sparkv1/DeleteTableRecordsAppTableSample.java">https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/sparkv1/DeleteTableRecordsAppTableSample.java</a>
   * ;
   */
  public DeleteTableRecordsAppTableResp deleteTableRecords(
      DeleteTableRecordsAppTableReq req, RequestOptions reqOptions) throws Exception {
    // 请求参数选项
    if (reqOptions == null) {
      reqOptions = new RequestOptions();
    }

    // 发起请求
    RawResponse httpResponse =
        Transport.send(
            config,
            reqOptions,
            "DELETE",
            "/open-apis/spark/v1/apps/:app_id/tables/:table_name/records",
            Sets.newHashSet(AccessTokenType.User),
            req);

    // 反序列化
    DeleteTableRecordsAppTableResp resp =
        UnmarshalRespUtil.unmarshalResp(httpResponse, DeleteTableRecordsAppTableResp.class);
    if (resp == null) {
      log.error(
          String.format(
              "%s,callError,req=%s,respHeader=%s,respStatusCode=%s,respBody=%s,",
              "/open-apis/spark/v1/apps/:app_id/tables/:table_name/records",
              Jsons.DEFAULT.toJson(req),
              Jsons.DEFAULT.toJson(httpResponse.getHeaders()),
              httpResponse.getStatusCode(),
              new String(httpResponse.getBody(), StandardCharsets.UTF_8)));
      throw new IllegalArgumentException("The result returned by the server is illegal");
    }

    resp.setRawResponse(httpResponse);
    resp.setRequest(req);

    return resp;
  }

  /**
   * 删除数据表中的记录，删除指定应用下数据表中符合filter筛选条件的记录，删除后记录不可恢复。
   *
   * <p>官网API文档链接:<a
   * href="https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=delete_table_records&project=spark&resource=app.table&version=v1">https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=delete_table_records&project=spark&resource=app.table&version=v1</a>
   * ;
   *
   * <p>使用Demo链接: <a
   * href="https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/sparkv1/DeleteTableRecordsAppTableSample.java">https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/sparkv1/DeleteTableRecordsAppTableSample.java</a>
   * ;
   */
  public DeleteTableRecordsAppTableResp deleteTableRecords(DeleteTableRecordsAppTableReq req)
      throws Exception {
    // 请求参数选项
    RequestOptions reqOptions = new RequestOptions();

    // 发起请求
    RawResponse httpResponse =
        Transport.send(
            config,
            reqOptions,
            "DELETE",
            "/open-apis/spark/v1/apps/:app_id/tables/:table_name/records",
            Sets.newHashSet(AccessTokenType.User),
            req);

    // 反序列化
    DeleteTableRecordsAppTableResp resp =
        UnmarshalRespUtil.unmarshalResp(httpResponse, DeleteTableRecordsAppTableResp.class);
    if (resp == null) {
      log.error(
          String.format(
              "%s,callError,req=%s,respHeader=%s,respStatusCode=%s,respBody=%s,",
              "/open-apis/spark/v1/apps/:app_id/tables/:table_name/records",
              Jsons.DEFAULT.toJson(req),
              Jsons.DEFAULT.toJson(httpResponse.getHeaders()),
              httpResponse.getStatusCode(),
              new String(httpResponse.getBody(), StandardCharsets.UTF_8)));
      throw new IllegalArgumentException("The result returned by the server is illegal");
    }

    resp.setRawResponse(httpResponse);
    resp.setRequest(req);

    return resp;
  }

  /**
   * 获取数据表详细信息，获取应用下的数据表详情，包含数据表名称、描述，以及数据表列信息等字段。
   *
   * <p>官网API文档链接:<a
   * href="https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=get_table_detail&project=spark&resource=app.table&version=v1">https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=get_table_detail&project=spark&resource=app.table&version=v1</a>
   * ;
   *
   * <p>使用Demo链接: <a
   * href="https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/sparkv1/GetTableDetailAppTableSample.java">https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/sparkv1/GetTableDetailAppTableSample.java</a>
   * ;
   */
  public GetTableDetailAppTableResp getTableDetail(
      GetTableDetailAppTableReq req, RequestOptions reqOptions) throws Exception {
    // 请求参数选项
    if (reqOptions == null) {
      reqOptions = new RequestOptions();
    }

    // 发起请求
    RawResponse httpResponse =
        Transport.send(
            config,
            reqOptions,
            "GET",
            "/open-apis/spark/v1/apps/:app_id/tables/:table_name",
            Sets.newHashSet(AccessTokenType.User),
            req);

    // 反序列化
    GetTableDetailAppTableResp resp =
        UnmarshalRespUtil.unmarshalResp(httpResponse, GetTableDetailAppTableResp.class);
    if (resp == null) {
      log.error(
          String.format(
              "%s,callError,req=%s,respHeader=%s,respStatusCode=%s,respBody=%s,",
              "/open-apis/spark/v1/apps/:app_id/tables/:table_name",
              Jsons.DEFAULT.toJson(req),
              Jsons.DEFAULT.toJson(httpResponse.getHeaders()),
              httpResponse.getStatusCode(),
              new String(httpResponse.getBody(), StandardCharsets.UTF_8)));
      throw new IllegalArgumentException("The result returned by the server is illegal");
    }

    resp.setRawResponse(httpResponse);
    resp.setRequest(req);

    return resp;
  }

  /**
   * 获取数据表详细信息，获取应用下的数据表详情，包含数据表名称、描述，以及数据表列信息等字段。
   *
   * <p>官网API文档链接:<a
   * href="https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=get_table_detail&project=spark&resource=app.table&version=v1">https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=get_table_detail&project=spark&resource=app.table&version=v1</a>
   * ;
   *
   * <p>使用Demo链接: <a
   * href="https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/sparkv1/GetTableDetailAppTableSample.java">https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/sparkv1/GetTableDetailAppTableSample.java</a>
   * ;
   */
  public GetTableDetailAppTableResp getTableDetail(GetTableDetailAppTableReq req) throws Exception {
    // 请求参数选项
    RequestOptions reqOptions = new RequestOptions();

    // 发起请求
    RawResponse httpResponse =
        Transport.send(
            config,
            reqOptions,
            "GET",
            "/open-apis/spark/v1/apps/:app_id/tables/:table_name",
            Sets.newHashSet(AccessTokenType.User),
            req);

    // 反序列化
    GetTableDetailAppTableResp resp =
        UnmarshalRespUtil.unmarshalResp(httpResponse, GetTableDetailAppTableResp.class);
    if (resp == null) {
      log.error(
          String.format(
              "%s,callError,req=%s,respHeader=%s,respStatusCode=%s,respBody=%s,",
              "/open-apis/spark/v1/apps/:app_id/tables/:table_name",
              Jsons.DEFAULT.toJson(req),
              Jsons.DEFAULT.toJson(httpResponse.getHeaders()),
              httpResponse.getStatusCode(),
              new String(httpResponse.getBody(), StandardCharsets.UTF_8)));
      throw new IllegalArgumentException("The result returned by the server is illegal");
    }

    resp.setRawResponse(httpResponse);
    resp.setRequest(req);

    return resp;
  }

  /**
   * 获取数据表列表，获取应用下的数据表列表，包含数据表名称、描述，以及数据表列信息等字段。
   *
   * <p>官网API文档链接:<a
   * href="https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=get_table_list&project=spark&resource=app.table&version=v1">https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=get_table_list&project=spark&resource=app.table&version=v1</a>
   * ;
   *
   * <p>使用Demo链接: <a
   * href="https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/sparkv1/GetTableListAppTableSample.java">https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/sparkv1/GetTableListAppTableSample.java</a>
   * ;
   */
  public GetTableListAppTableResp getTableList(
      GetTableListAppTableReq req, RequestOptions reqOptions) throws Exception {
    // 请求参数选项
    if (reqOptions == null) {
      reqOptions = new RequestOptions();
    }

    // 发起请求
    RawResponse httpResponse =
        Transport.send(
            config,
            reqOptions,
            "GET",
            "/open-apis/spark/v1/apps/:app_id/tables",
            Sets.newHashSet(AccessTokenType.User),
            req);

    // 反序列化
    GetTableListAppTableResp resp =
        UnmarshalRespUtil.unmarshalResp(httpResponse, GetTableListAppTableResp.class);
    if (resp == null) {
      log.error(
          String.format(
              "%s,callError,req=%s,respHeader=%s,respStatusCode=%s,respBody=%s,",
              "/open-apis/spark/v1/apps/:app_id/tables",
              Jsons.DEFAULT.toJson(req),
              Jsons.DEFAULT.toJson(httpResponse.getHeaders()),
              httpResponse.getStatusCode(),
              new String(httpResponse.getBody(), StandardCharsets.UTF_8)));
      throw new IllegalArgumentException("The result returned by the server is illegal");
    }

    resp.setRawResponse(httpResponse);
    resp.setRequest(req);

    return resp;
  }

  /**
   * 获取数据表列表，获取应用下的数据表列表，包含数据表名称、描述，以及数据表列信息等字段。
   *
   * <p>官网API文档链接:<a
   * href="https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=get_table_list&project=spark&resource=app.table&version=v1">https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=get_table_list&project=spark&resource=app.table&version=v1</a>
   * ;
   *
   * <p>使用Demo链接: <a
   * href="https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/sparkv1/GetTableListAppTableSample.java">https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/sparkv1/GetTableListAppTableSample.java</a>
   * ;
   */
  public GetTableListAppTableResp getTableList(GetTableListAppTableReq req) throws Exception {
    // 请求参数选项
    RequestOptions reqOptions = new RequestOptions();

    // 发起请求
    RawResponse httpResponse =
        Transport.send(
            config,
            reqOptions,
            "GET",
            "/open-apis/spark/v1/apps/:app_id/tables",
            Sets.newHashSet(AccessTokenType.User),
            req);

    // 反序列化
    GetTableListAppTableResp resp =
        UnmarshalRespUtil.unmarshalResp(httpResponse, GetTableListAppTableResp.class);
    if (resp == null) {
      log.error(
          String.format(
              "%s,callError,req=%s,respHeader=%s,respStatusCode=%s,respBody=%s,",
              "/open-apis/spark/v1/apps/:app_id/tables",
              Jsons.DEFAULT.toJson(req),
              Jsons.DEFAULT.toJson(httpResponse.getHeaders()),
              httpResponse.getStatusCode(),
              new String(httpResponse.getBody(), StandardCharsets.UTF_8)));
      throw new IllegalArgumentException("The result returned by the server is illegal");
    }

    resp.setRawResponse(httpResponse);
    resp.setRequest(req);

    return resp;
  }

  /**
   * 查询数据表数据记录，查询应用下的数据表数据记录，包括指定列、字段值及分页信息，适用于需要获取应用下某数据表数据的记录、展示等场景。
   *
   * <p>官网API文档链接:<a
   * href="https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=get_table_record_list&project=spark&resource=app.table&version=v1">https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=get_table_record_list&project=spark&resource=app.table&version=v1</a>
   * ;
   *
   * <p>使用Demo链接: <a
   * href="https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/sparkv1/GetTableRecordListAppTableSample.java">https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/sparkv1/GetTableRecordListAppTableSample.java</a>
   * ;
   */
  public GetTableRecordListAppTableResp getTableRecordList(
      GetTableRecordListAppTableReq req, RequestOptions reqOptions) throws Exception {
    // 请求参数选项
    if (reqOptions == null) {
      reqOptions = new RequestOptions();
    }

    // 发起请求
    RawResponse httpResponse =
        Transport.send(
            config,
            reqOptions,
            "GET",
            "/open-apis/spark/v1/apps/:app_id/tables/:table_name/records",
            Sets.newHashSet(AccessTokenType.User),
            req);

    // 反序列化
    GetTableRecordListAppTableResp resp =
        UnmarshalRespUtil.unmarshalResp(httpResponse, GetTableRecordListAppTableResp.class);
    if (resp == null) {
      log.error(
          String.format(
              "%s,callError,req=%s,respHeader=%s,respStatusCode=%s,respBody=%s,",
              "/open-apis/spark/v1/apps/:app_id/tables/:table_name/records",
              Jsons.DEFAULT.toJson(req),
              Jsons.DEFAULT.toJson(httpResponse.getHeaders()),
              httpResponse.getStatusCode(),
              new String(httpResponse.getBody(), StandardCharsets.UTF_8)));
      throw new IllegalArgumentException("The result returned by the server is illegal");
    }

    resp.setRawResponse(httpResponse);
    resp.setRequest(req);

    return resp;
  }

  /**
   * 查询数据表数据记录，查询应用下的数据表数据记录，包括指定列、字段值及分页信息，适用于需要获取应用下某数据表数据的记录、展示等场景。
   *
   * <p>官网API文档链接:<a
   * href="https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=get_table_record_list&project=spark&resource=app.table&version=v1">https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=get_table_record_list&project=spark&resource=app.table&version=v1</a>
   * ;
   *
   * <p>使用Demo链接: <a
   * href="https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/sparkv1/GetTableRecordListAppTableSample.java">https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/sparkv1/GetTableRecordListAppTableSample.java</a>
   * ;
   */
  public GetTableRecordListAppTableResp getTableRecordList(GetTableRecordListAppTableReq req)
      throws Exception {
    // 请求参数选项
    RequestOptions reqOptions = new RequestOptions();

    // 发起请求
    RawResponse httpResponse =
        Transport.send(
            config,
            reqOptions,
            "GET",
            "/open-apis/spark/v1/apps/:app_id/tables/:table_name/records",
            Sets.newHashSet(AccessTokenType.User),
            req);

    // 反序列化
    GetTableRecordListAppTableResp resp =
        UnmarshalRespUtil.unmarshalResp(httpResponse, GetTableRecordListAppTableResp.class);
    if (resp == null) {
      log.error(
          String.format(
              "%s,callError,req=%s,respHeader=%s,respStatusCode=%s,respBody=%s,",
              "/open-apis/spark/v1/apps/:app_id/tables/:table_name/records",
              Jsons.DEFAULT.toJson(req),
              Jsons.DEFAULT.toJson(httpResponse.getHeaders()),
              httpResponse.getStatusCode(),
              new String(httpResponse.getBody(), StandardCharsets.UTF_8)));
      throw new IllegalArgumentException("The result returned by the server is illegal");
    }

    resp.setRawResponse(httpResponse);
    resp.setRequest(req);

    return resp;
  }

  /**
   * 按条件更新数据表中的记录，将数据表中符合filter条件的记录更新为record参数指定的内容。
   *
   * <p>官网API文档链接:<a
   * href="https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=patch_table_records&project=spark&resource=app.table&version=v1">https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=patch_table_records&project=spark&resource=app.table&version=v1</a>
   * ;
   *
   * <p>使用Demo链接: <a
   * href="https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/sparkv1/PatchTableRecordsAppTableSample.java">https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/sparkv1/PatchTableRecordsAppTableSample.java</a>
   * ;
   */
  public PatchTableRecordsAppTableResp patchTableRecords(
      PatchTableRecordsAppTableReq req, RequestOptions reqOptions) throws Exception {
    // 请求参数选项
    if (reqOptions == null) {
      reqOptions = new RequestOptions();
    }

    // 发起请求
    RawResponse httpResponse =
        Transport.send(
            config,
            reqOptions,
            "PATCH",
            "/open-apis/spark/v1/apps/:app_id/tables/:table_name/records",
            Sets.newHashSet(AccessTokenType.User),
            req);

    // 反序列化
    PatchTableRecordsAppTableResp resp =
        UnmarshalRespUtil.unmarshalResp(httpResponse, PatchTableRecordsAppTableResp.class);
    if (resp == null) {
      log.error(
          String.format(
              "%s,callError,req=%s,respHeader=%s,respStatusCode=%s,respBody=%s,",
              "/open-apis/spark/v1/apps/:app_id/tables/:table_name/records",
              Jsons.DEFAULT.toJson(req),
              Jsons.DEFAULT.toJson(httpResponse.getHeaders()),
              httpResponse.getStatusCode(),
              new String(httpResponse.getBody(), StandardCharsets.UTF_8)));
      throw new IllegalArgumentException("The result returned by the server is illegal");
    }

    resp.setRawResponse(httpResponse);
    resp.setRequest(req);

    return resp;
  }

  /**
   * 按条件更新数据表中的记录，将数据表中符合filter条件的记录更新为record参数指定的内容。
   *
   * <p>官网API文档链接:<a
   * href="https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=patch_table_records&project=spark&resource=app.table&version=v1">https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=patch_table_records&project=spark&resource=app.table&version=v1</a>
   * ;
   *
   * <p>使用Demo链接: <a
   * href="https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/sparkv1/PatchTableRecordsAppTableSample.java">https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/sparkv1/PatchTableRecordsAppTableSample.java</a>
   * ;
   */
  public PatchTableRecordsAppTableResp patchTableRecords(PatchTableRecordsAppTableReq req)
      throws Exception {
    // 请求参数选项
    RequestOptions reqOptions = new RequestOptions();

    // 发起请求
    RawResponse httpResponse =
        Transport.send(
            config,
            reqOptions,
            "PATCH",
            "/open-apis/spark/v1/apps/:app_id/tables/:table_name/records",
            Sets.newHashSet(AccessTokenType.User),
            req);

    // 反序列化
    PatchTableRecordsAppTableResp resp =
        UnmarshalRespUtil.unmarshalResp(httpResponse, PatchTableRecordsAppTableResp.class);
    if (resp == null) {
      log.error(
          String.format(
              "%s,callError,req=%s,respHeader=%s,respStatusCode=%s,respBody=%s,",
              "/open-apis/spark/v1/apps/:app_id/tables/:table_name/records",
              Jsons.DEFAULT.toJson(req),
              Jsons.DEFAULT.toJson(httpResponse.getHeaders()),
              httpResponse.getStatusCode(),
              new String(httpResponse.getBody(), StandardCharsets.UTF_8)));
      throw new IllegalArgumentException("The result returned by the server is illegal");
    }

    resp.setRawResponse(httpResponse);
    resp.setRequest(req);

    return resp;
  }

  /**
   * 向数据表中添加或更新记录，向应用下的数据表中添加或更新记录。
   *
   * <p>官网API文档链接:<a
   * href="https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=post_table_records&project=spark&resource=app.table&version=v1">https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=post_table_records&project=spark&resource=app.table&version=v1</a>
   * ;
   *
   * <p>使用Demo链接: <a
   * href="https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/sparkv1/PostTableRecordsAppTableSample.java">https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/sparkv1/PostTableRecordsAppTableSample.java</a>
   * ;
   */
  public PostTableRecordsAppTableResp postTableRecords(
      PostTableRecordsAppTableReq req, RequestOptions reqOptions) throws Exception {
    // 请求参数选项
    if (reqOptions == null) {
      reqOptions = new RequestOptions();
    }

    // 发起请求
    RawResponse httpResponse =
        Transport.send(
            config,
            reqOptions,
            "POST",
            "/open-apis/spark/v1/apps/:app_id/tables/:table_name/records",
            Sets.newHashSet(AccessTokenType.User),
            req);

    // 反序列化
    PostTableRecordsAppTableResp resp =
        UnmarshalRespUtil.unmarshalResp(httpResponse, PostTableRecordsAppTableResp.class);
    if (resp == null) {
      log.error(
          String.format(
              "%s,callError,req=%s,respHeader=%s,respStatusCode=%s,respBody=%s,",
              "/open-apis/spark/v1/apps/:app_id/tables/:table_name/records",
              Jsons.DEFAULT.toJson(req),
              Jsons.DEFAULT.toJson(httpResponse.getHeaders()),
              httpResponse.getStatusCode(),
              new String(httpResponse.getBody(), StandardCharsets.UTF_8)));
      throw new IllegalArgumentException("The result returned by the server is illegal");
    }

    resp.setRawResponse(httpResponse);
    resp.setRequest(req);

    return resp;
  }

  /**
   * 向数据表中添加或更新记录，向应用下的数据表中添加或更新记录。
   *
   * <p>官网API文档链接:<a
   * href="https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=post_table_records&project=spark&resource=app.table&version=v1">https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=post_table_records&project=spark&resource=app.table&version=v1</a>
   * ;
   *
   * <p>使用Demo链接: <a
   * href="https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/sparkv1/PostTableRecordsAppTableSample.java">https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/sparkv1/PostTableRecordsAppTableSample.java</a>
   * ;
   */
  public PostTableRecordsAppTableResp postTableRecords(PostTableRecordsAppTableReq req)
      throws Exception {
    // 请求参数选项
    RequestOptions reqOptions = new RequestOptions();

    // 发起请求
    RawResponse httpResponse =
        Transport.send(
            config,
            reqOptions,
            "POST",
            "/open-apis/spark/v1/apps/:app_id/tables/:table_name/records",
            Sets.newHashSet(AccessTokenType.User),
            req);

    // 反序列化
    PostTableRecordsAppTableResp resp =
        UnmarshalRespUtil.unmarshalResp(httpResponse, PostTableRecordsAppTableResp.class);
    if (resp == null) {
      log.error(
          String.format(
              "%s,callError,req=%s,respHeader=%s,respStatusCode=%s,respBody=%s,",
              "/open-apis/spark/v1/apps/:app_id/tables/:table_name/records",
              Jsons.DEFAULT.toJson(req),
              Jsons.DEFAULT.toJson(httpResponse.getHeaders()),
              httpResponse.getStatusCode(),
              new String(httpResponse.getBody(), StandardCharsets.UTF_8)));
      throw new IllegalArgumentException("The result returned by the server is illegal");
    }

    resp.setRawResponse(httpResponse);
    resp.setRequest(req);

    return resp;
  }
}
