// Code generated by lark suite oapi sdk gen
package com.lark.oapi.service.task.v1.model;

import com.google.gson.annotations.SerializedName;
import com.lark.oapi.core.response.BaseResponse;

public class ListTaskResp extends BaseResponse {

  @SerializedName("data")
  private ListTask body;

  public ListTask getListTask() {
    return this.body;
  }

  public void setListTask(ListTask body) {
    this.body = body;
  }
}
