// Code generated by lark suite oapi sdk gen
/*
 * MIT License
 *
 * Copyright (c) 2022 Lark Technologies Pte. Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice, shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.lark.oapi.service.hire.v2.model;

import com.google.gson.annotations.SerializedName;

public class IdNameObject {
  /**
   * 面试官 ID，与入参 `user_id_type` 类型一致
   *
   * <p>示例值：7171693733661327364
   */
  @SerializedName("id")
  private String id;

  /**
   * 最高职级建议
   *
   * <p>示例值：
   */
  @SerializedName("name")
  private I18n name;

  public String getId() {
    return this.id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public I18n getName() {
    return this.name;
  }

  public void setName(I18n name) {
    this.name = name;
  }

  // builder 开始
  public IdNameObject() {}

  public IdNameObject(Builder builder) {
    /**
     * 面试官 ID，与入参 `user_id_type` 类型一致
     *
     * <p>示例值：7171693733661327364
     */
    this.id = builder.id;
    /**
     * 最高职级建议
     *
     * <p>示例值：
     */
    this.name = builder.name;
  }

  public static class Builder {
    /**
     * 面试官 ID，与入参 `user_id_type` 类型一致
     *
     * <p>示例值：7171693733661327364
     */
    private String id;

    /**
     * 最高职级建议
     *
     * <p>示例值：
     */
    private I18n name;

    /**
     * 面试官 ID，与入参 `user_id_type` 类型一致
     *
     * <p>示例值：7171693733661327364
     *
     * @param id
     * @return
     */
    public Builder id(String id) {
      this.id = id;
      return this;
    }

    /**
     * 最高职级建议
     *
     * <p>示例值：
     *
     * @param name
     * @return
     */
    public Builder name(I18n name) {
      this.name = name;
      return this;
    }

    public IdNameObject build() {
      return new IdNameObject(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
