// Code generated by lark suite oapi sdk gen
package com.larksuite.oapi.service.vc.v1.model;

import com.google.gson.annotations.SerializedName;

public class KickoutMeetingReqBody {
    @SerializedName("kickout_users")
    private MeetingUser[] kickoutUsers;

    // builder 开始
    public KickoutMeetingReqBody() {
    }

    public KickoutMeetingReqBody(Builder builder) {
        this.kickoutUsers = builder.kickoutUsers;
    }

    public static Builder newBuilder() {
        return new Builder();
    }

    public MeetingUser[] getKickoutUsers() {
        return this.kickoutUsers;
    }

    public void setKickoutUsers(MeetingUser[] kickoutUsers) {
        this.kickoutUsers = kickoutUsers;
    }

    public static class Builder {
        private MeetingUser[] kickoutUsers;

        public Builder kickoutUsers(MeetingUser[] kickoutUsers) {
            this.kickoutUsers = kickoutUsers;
            return this;
        }


        public KickoutMeetingReqBody build() {
            return new KickoutMeetingReqBody(this);
        }
    }
}
