// Code generated by lark suite oapi sdk gen
package com.larksuite.oapi.service.vc.v1.model;
import com.google.gson.annotations.SerializedName;

public class MeetingRecordingGetResult {
    @SerializedName("recording")
    private MeetingRecording recording;

    public MeetingRecording getRecording() {
        return this.recording;
    }

    public void setRecording(MeetingRecording recording) {
        this.recording = recording;
    }

}
