// Code generated by lark suite oapi sdk gen
package com.lark.oapi.service.vc.v1.model;

import com.google.gson.annotations.SerializedName;
import com.lark.oapi.core.response.BaseResponse;

public class GetActiveMeetingReserveResp extends BaseResponse {

  @SerializedName("data")
  private GetActiveMeetingReserveDTO body;

  public GetActiveMeetingReserveDTO getGetActiveMeetingReserveDTO() {
    return this.body;
  }

  public void setGetActiveMeetingReserveDTO(GetActiveMeetingReserveDTO body) {
    this.body = body;
  }
}
