// Code generated by lark suite oapi sdk gen
package com.lark.oapi.service.vc.v1.model;

import com.google.gson.annotations.SerializedName;
import com.lark.oapi.core.response.BaseResponse;

public class InviteMeetingResp extends BaseResponse {

  @SerializedName("data")
  private InviteMeetingDTO body;

  public InviteMeetingDTO getInviteMeetingDTO() {
    return this.body;
  }

  public void setInviteMeetingDTO(InviteMeetingDTO body) {
    this.body = body;
  }
}
