// Code generated by lark suite oapi sdk gen
/*
 * MIT License
 *
 * Copyright (c) 2022 Lark Technologies Pte. Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice, shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.lark.oapi.service.aily.v1.model;

import com.google.gson.annotations.SerializedName;
import com.lark.oapi.core.annotation.Body;
import com.lark.oapi.core.annotation.Path;
import com.lark.oapi.core.annotation.Query;
import com.lark.oapi.service.aily.v1.enums.*;

public class CreateAppDataAssetReq {
  /**
   * 应用环境，枚举值：;- `online`：线上环境（默认值）;- `dev`：开发环境；目前只支持 `dev`
   *
   * <p>示例值：dev
   */
  @Query
  @SerializedName("tenant_type")
  private String tenantType;

  public String getTenantType() {
    return this.tenantType;
  }

  public void setTenantType(String tenantType) {
    this.tenantType = tenantType;
  }

  /**
   * Aily 平台的应用的APPID，可以直接从 Aily 应用的URL中获取。获取示例：/ai/{APPID}
   *
   * <p>示例值：spring_dfasdf__c
   */
  @Path
  @SerializedName("app_id")
  private String appId;

  public String getAppId() {
    return this.appId;
  }

  public void setAppId(String appId) {
    this.appId = appId;
  }

  @Body private CreateAppDataAssetReqBody body;

  public CreateAppDataAssetReqBody getCreateAppDataAssetReqBody() {
    return this.body;
  }

  public void setCreateAppDataAssetReqBody(CreateAppDataAssetReqBody body) {
    this.body = body;
  }

  // builder 开始
  public CreateAppDataAssetReq() {}

  public CreateAppDataAssetReq(Builder builder) {
    /**
     * 应用环境，枚举值：;- `online`：线上环境（默认值）;- `dev`：开发环境；目前只支持 `dev`
     *
     * <p>示例值：dev
     */
    this.tenantType = builder.tenantType;
    /**
     * Aily 平台的应用的APPID，可以直接从 Aily 应用的URL中获取。获取示例：/ai/{APPID}
     *
     * <p>示例值：spring_dfasdf__c
     */
    this.appId = builder.appId;
    this.body = builder.body;
  }

  public static class Builder {
    private String tenantType; // 应用环境，枚举值：;- `online`：线上环境（默认值）;- `dev`：开发环境；目前只支持 `dev`

    /**
     * 应用环境，枚举值：;- `online`：线上环境（默认值）;- `dev`：开发环境；目前只支持 `dev`
     *
     * <p>示例值：dev
     *
     * @param tenantType
     * @return
     */
    public Builder tenantType(String tenantType) {
      this.tenantType = tenantType;
      return this;
    }

    private String appId; // Aily 平台的应用的APPID，可以直接从 Aily 应用的URL中获取。获取示例：/ai/{APPID}

    /**
     * Aily 平台的应用的APPID，可以直接从 Aily 应用的URL中获取。获取示例：/ai/{APPID}
     *
     * <p>示例值：spring_dfasdf__c
     *
     * @param appId
     * @return
     */
    public Builder appId(String appId) {
      this.appId = appId;
      return this;
    }

    private CreateAppDataAssetReqBody body;

    public CreateAppDataAssetReqBody getCreateAppDataAssetReqBody() {
      return this.body;
    }

    /**
     * body
     *
     * @param body
     * @return
     */
    public Builder createAppDataAssetReqBody(CreateAppDataAssetReqBody body) {
      this.body = body;
      return this;
    }

    public CreateAppDataAssetReq build() {
      return new CreateAppDataAssetReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
