// Code generated by lark suite oapi sdk gen
/*
 * MIT License
 *
 * Copyright (c) 2022 Lark Technologies Pte. Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice, shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.lark.oapi.service.corehr.v2.model;

import com.google.gson.annotations.SerializedName;

public class BasicJobData {
    /**
     * 任职信息 ID
     * <p> 示例值：1000000
     */
    @SerializedName("job_data_id")
    private String jobDataId;
    /**
     * 雇佣 ID
     * <p> 示例值：6893014062142064135
     */
    @SerializedName("employment_id")
    private String employmentId;

    // builder 开始
    public BasicJobData() {
    }

    public BasicJobData(Builder builder) {
        /**
         * 任职信息 ID
         * <p> 示例值：1000000
         */
        this.jobDataId = builder.jobDataId;
        /**
         * 雇佣 ID
         * <p> 示例值：6893014062142064135
         */
        this.employmentId = builder.employmentId;
    }

    public static Builder newBuilder() {
        return new Builder();
    }

    public String getJobDataId() {
        return this.jobDataId;
    }

    public void setJobDataId(String jobDataId) {
        this.jobDataId = jobDataId;
    }

    public String getEmploymentId() {
        return this.employmentId;
    }

    public void setEmploymentId(String employmentId) {
        this.employmentId = employmentId;
    }

    public static class Builder {
        /**
         * 任职信息 ID
         * <p> 示例值：1000000
         */
        private String jobDataId;
        /**
         * 雇佣 ID
         * <p> 示例值：6893014062142064135
         */
        private String employmentId;

        /**
         * 任职信息 ID
         * <p> 示例值：1000000
         *
         * @param jobDataId
         * @return
         */
        public Builder jobDataId(String jobDataId) {
            this.jobDataId = jobDataId;
            return this;
        }


        /**
         * 雇佣 ID
         * <p> 示例值：6893014062142064135
         *
         * @param employmentId
         * @return
         */
        public Builder employmentId(String employmentId) {
            this.employmentId = employmentId;
            return this;
        }


        public BasicJobData build() {
            return new BasicJobData(this);
        }
    }
}
