// Code generated by lark suite oapi sdk gen
/*
 * MIT License
 *
 * Copyright (c) 2022 Lark Technologies Pte. Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice, shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.lark.oapi.service.corehr.v2.model;

import com.google.gson.annotations.SerializedName;
import com.lark.oapi.service.corehr.v2.enums.*;

public class EmploymentColumnValueForAgent {
  /**
   * 字段key
   *
   * <p>示例值：employment.work_location
   */
  @SerializedName("field_key")
  private String fieldKey;

  /**
   * 字段值
   *
   * <p>示例值：7109475834939434
   */
  @SerializedName("column_value")
  private String columnValue;

  /**
   * 是否有权限
   *
   * <p>示例值：false
   */
  @SerializedName("has_permission")
  private Boolean hasPermission;

  public String getFieldKey() {
    return this.fieldKey;
  }

  public void setFieldKey(String fieldKey) {
    this.fieldKey = fieldKey;
  }

  public String getColumnValue() {
    return this.columnValue;
  }

  public void setColumnValue(String columnValue) {
    this.columnValue = columnValue;
  }

  public Boolean getHasPermission() {
    return this.hasPermission;
  }

  public void setHasPermission(Boolean hasPermission) {
    this.hasPermission = hasPermission;
  }

  // builder 开始
  public EmploymentColumnValueForAgent() {}

  public EmploymentColumnValueForAgent(Builder builder) {
    /**
     * 字段key
     *
     * <p>示例值：employment.work_location
     */
    this.fieldKey = builder.fieldKey;
    /**
     * 字段值
     *
     * <p>示例值：7109475834939434
     */
    this.columnValue = builder.columnValue;
    /**
     * 是否有权限
     *
     * <p>示例值：false
     */
    this.hasPermission = builder.hasPermission;
  }

  public static class Builder {
    /**
     * 字段key
     *
     * <p>示例值：employment.work_location
     */
    private String fieldKey;

    /**
     * 字段值
     *
     * <p>示例值：7109475834939434
     */
    private String columnValue;

    /**
     * 是否有权限
     *
     * <p>示例值：false
     */
    private Boolean hasPermission;

    /**
     * 字段key
     *
     * <p>示例值：employment.work_location
     *
     * @param fieldKey
     * @return
     */
    public Builder fieldKey(String fieldKey) {
      this.fieldKey = fieldKey;
      return this;
    }

    /**
     * 字段值
     *
     * <p>示例值：7109475834939434
     *
     * @param columnValue
     * @return
     */
    public Builder columnValue(String columnValue) {
      this.columnValue = columnValue;
      return this;
    }

    /**
     * 是否有权限
     *
     * <p>示例值：false
     *
     * @param hasPermission
     * @return
     */
    public Builder hasPermission(Boolean hasPermission) {
      this.hasPermission = hasPermission;
      return this;
    }

    public EmploymentColumnValueForAgent build() {
      return new EmploymentColumnValueForAgent(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
