// Code generated by lark suite oapi sdk gen
/*
 * MIT License
 *
 * Copyright (c) 2022 Lark Technologies Pte. Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice, shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.lark.oapi.service.corehr.v2.model;

import com.google.gson.annotations.SerializedName;
import com.lark.oapi.service.corehr.v2.enums.*;

public class OrgRole {
  /**
   * 角色key; - 可以通过页面「飞书人事-设置-组织配置」选择对应自定义组织，「字段配置-字段编码」获取;
   *
   * <p>示例值：hcm_corehr_xxx
   */
  @SerializedName("api_name")
  private String apiName;

  /**
   * 角色ID; -
   * 可以通过[批量获取角色列表](https://open.larkoffice.com/document/server-docs/corehr-v1/authorization/list)
   * 获取，数据为返回数据中的 data.items.id 值。筛选条件data.items.group_type == 3（组织角色），data.items.org_truncation
   * 关联的组织有且仅有一个，data.items.org_truncation.org_key 等于当前查询自定义组织 object_api_name
   *
   * <p>示例值：7034393015968122400
   */
  @SerializedName("security_group_id")
  private String securityGroupId;

  /**
   * 直接授权的员工 ID 列表;- 返回的 ID 类型为 ==people_corehr_id==;-
   * 详细信息可通过[【搜索员工信息】](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/employee/search)
   * 或
   * [【批量查询员工】](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/employee/batch_get)
   * 接口获取
   *
   * <p>示例值：
   */
  @SerializedName("employment_ids")
  private String[] employmentIds;

  /**
   * 由于有上级组织权限而自动获取下级组织权限的员工 ID 列表;- 返回的 ID 类型为 ==people_corehr_id==;-
   * 详细信息可通过[【搜索员工信息】](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/employee/search)
   * 或
   * [【批量查询员工】](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/employee/batch_get)
   * 接口获取
   *
   * <p>示例值：
   */
  @SerializedName("inherit_employment_ids")
  private String[] inheritEmploymentIds;

  public String getApiName() {
    return this.apiName;
  }

  public void setApiName(String apiName) {
    this.apiName = apiName;
  }

  public String getSecurityGroupId() {
    return this.securityGroupId;
  }

  public void setSecurityGroupId(String securityGroupId) {
    this.securityGroupId = securityGroupId;
  }

  public String[] getEmploymentIds() {
    return this.employmentIds;
  }

  public void setEmploymentIds(String[] employmentIds) {
    this.employmentIds = employmentIds;
  }

  public String[] getInheritEmploymentIds() {
    return this.inheritEmploymentIds;
  }

  public void setInheritEmploymentIds(String[] inheritEmploymentIds) {
    this.inheritEmploymentIds = inheritEmploymentIds;
  }

  // builder 开始
  public OrgRole() {}

  public OrgRole(Builder builder) {
    /**
     * 角色key; - 可以通过页面「飞书人事-设置-组织配置」选择对应自定义组织，「字段配置-字段编码」获取;
     *
     * <p>示例值：hcm_corehr_xxx
     */
    this.apiName = builder.apiName;
    /**
     * 角色ID; -
     * 可以通过[批量获取角色列表](https://open.larkoffice.com/document/server-docs/corehr-v1/authorization/list)
     * 获取，数据为返回数据中的 data.items.id 值。筛选条件data.items.group_type == 3（组织角色），data.items.org_truncation
     * 关联的组织有且仅有一个，data.items.org_truncation.org_key 等于当前查询自定义组织 object_api_name
     *
     * <p>示例值：7034393015968122400
     */
    this.securityGroupId = builder.securityGroupId;
    /**
     * 直接授权的员工 ID 列表;- 返回的 ID 类型为 ==people_corehr_id==;-
     * 详细信息可通过[【搜索员工信息】](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/employee/search)
     * 或
     * [【批量查询员工】](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/employee/batch_get)
     * 接口获取
     *
     * <p>示例值：
     */
    this.employmentIds = builder.employmentIds;
    /**
     * 由于有上级组织权限而自动获取下级组织权限的员工 ID 列表;- 返回的 ID 类型为 ==people_corehr_id==;-
     * 详细信息可通过[【搜索员工信息】](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/employee/search)
     * 或
     * [【批量查询员工】](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/employee/batch_get)
     * 接口获取
     *
     * <p>示例值：
     */
    this.inheritEmploymentIds = builder.inheritEmploymentIds;
  }

  public static class Builder {
    /**
     * 角色key; - 可以通过页面「飞书人事-设置-组织配置」选择对应自定义组织，「字段配置-字段编码」获取;
     *
     * <p>示例值：hcm_corehr_xxx
     */
    private String apiName;

    /**
     * 角色ID; -
     * 可以通过[批量获取角色列表](https://open.larkoffice.com/document/server-docs/corehr-v1/authorization/list)
     * 获取，数据为返回数据中的 data.items.id 值。筛选条件data.items.group_type == 3（组织角色），data.items.org_truncation
     * 关联的组织有且仅有一个，data.items.org_truncation.org_key 等于当前查询自定义组织 object_api_name
     *
     * <p>示例值：7034393015968122400
     */
    private String securityGroupId;

    /**
     * 直接授权的员工 ID 列表;- 返回的 ID 类型为 ==people_corehr_id==;-
     * 详细信息可通过[【搜索员工信息】](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/employee/search)
     * 或
     * [【批量查询员工】](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/employee/batch_get)
     * 接口获取
     *
     * <p>示例值：
     */
    private String[] employmentIds;

    /**
     * 由于有上级组织权限而自动获取下级组织权限的员工 ID 列表;- 返回的 ID 类型为 ==people_corehr_id==;-
     * 详细信息可通过[【搜索员工信息】](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/employee/search)
     * 或
     * [【批量查询员工】](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/employee/batch_get)
     * 接口获取
     *
     * <p>示例值：
     */
    private String[] inheritEmploymentIds;

    /**
     * 角色key; - 可以通过页面「飞书人事-设置-组织配置」选择对应自定义组织，「字段配置-字段编码」获取;
     *
     * <p>示例值：hcm_corehr_xxx
     *
     * @param apiName
     * @return
     */
    public Builder apiName(String apiName) {
      this.apiName = apiName;
      return this;
    }

    /**
     * 角色ID; -
     * 可以通过[批量获取角色列表](https://open.larkoffice.com/document/server-docs/corehr-v1/authorization/list)
     * 获取，数据为返回数据中的 data.items.id 值。筛选条件data.items.group_type == 3（组织角色），data.items.org_truncation
     * 关联的组织有且仅有一个，data.items.org_truncation.org_key 等于当前查询自定义组织 object_api_name
     *
     * <p>示例值：7034393015968122400
     *
     * @param securityGroupId
     * @return
     */
    public Builder securityGroupId(String securityGroupId) {
      this.securityGroupId = securityGroupId;
      return this;
    }

    /**
     * 直接授权的员工 ID 列表;- 返回的 ID 类型为 ==people_corehr_id==;-
     * 详细信息可通过[【搜索员工信息】](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/employee/search)
     * 或
     * [【批量查询员工】](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/employee/batch_get)
     * 接口获取
     *
     * <p>示例值：
     *
     * @param employmentIds
     * @return
     */
    public Builder employmentIds(String[] employmentIds) {
      this.employmentIds = employmentIds;
      return this;
    }

    /**
     * 由于有上级组织权限而自动获取下级组织权限的员工 ID 列表;- 返回的 ID 类型为 ==people_corehr_id==;-
     * 详细信息可通过[【搜索员工信息】](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/employee/search)
     * 或
     * [【批量查询员工】](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/employee/batch_get)
     * 接口获取
     *
     * <p>示例值：
     *
     * @param inheritEmploymentIds
     * @return
     */
    public Builder inheritEmploymentIds(String[] inheritEmploymentIds) {
      this.inheritEmploymentIds = inheritEmploymentIds;
      return this;
    }

    public OrgRole build() {
      return new OrgRole(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
