// Code generated by lark suite oapi sdk gen
/*
 * MIT License
 *
 * Copyright (c) 2022 Lark Technologies Pte. Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice, shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.lark.oapi.service.corehr.v2.model;

import com.google.gson.annotations.SerializedName;

public class SignatureCustomFieldValue {
    /**
     * 自定义字段的值
     * <p> 示例值：test
     */
    @SerializedName("text_value")
    private String textValue;
    /**
     * 自定义字段的值对应的多语value
     * <p> 示例值：
     */
    @SerializedName("multilingual_value")
    private SignatureCustomFieldValueMultilingualValue multilingualValue;

    // builder 开始
    public SignatureCustomFieldValue() {
    }

    public SignatureCustomFieldValue(Builder builder) {
        /**
         * 自定义字段的值
         * <p> 示例值：test
         */
        this.textValue = builder.textValue;
        /**
         * 自定义字段的值对应的多语value
         * <p> 示例值：
         */
        this.multilingualValue = builder.multilingualValue;
    }

    public static Builder newBuilder() {
        return new Builder();
    }

    public String getTextValue() {
        return this.textValue;
    }

    public void setTextValue(String textValue) {
        this.textValue = textValue;
    }

    public SignatureCustomFieldValueMultilingualValue getMultilingualValue() {
        return this.multilingualValue;
    }

    public void setMultilingualValue(SignatureCustomFieldValueMultilingualValue multilingualValue) {
        this.multilingualValue = multilingualValue;
    }

    public static class Builder {
        /**
         * 自定义字段的值
         * <p> 示例值：test
         */
        private String textValue;
        /**
         * 自定义字段的值对应的多语value
         * <p> 示例值：
         */
        private SignatureCustomFieldValueMultilingualValue multilingualValue;

        /**
         * 自定义字段的值
         * <p> 示例值：test
         *
         * @param textValue
         * @return
         */
        public Builder textValue(String textValue) {
            this.textValue = textValue;
            return this;
        }


        /**
         * 自定义字段的值对应的多语value
         * <p> 示例值：
         *
         * @param multilingualValue
         * @return
         */
        public Builder multilingualValue(SignatureCustomFieldValueMultilingualValue multilingualValue) {
            this.multilingualValue = multilingualValue;
            return this;
        }


        public SignatureCustomFieldValue build() {
            return new SignatureCustomFieldValue(this);
        }
    }
}
