// Code generated by lark suite oapi sdk gen
/*
 * MIT License
 *
 * Copyright (c) 2022 Lark Technologies Pte. Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice, shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.lark.oapi.service.corehr.v2.resource;

import com.lark.oapi.core.Config;
import com.lark.oapi.core.Transport;
import com.lark.oapi.core.request.RequestOptions;
import com.lark.oapi.core.response.RawResponse;
import com.lark.oapi.core.token.AccessTokenType;
import com.lark.oapi.core.utils.Jsons;
import com.lark.oapi.core.utils.Sets;
import com.lark.oapi.core.utils.UnmarshalRespUtil;
import com.lark.oapi.service.corehr.v2.model.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Draft {
  private static final Logger log = LoggerFactory.getLogger(Draft.class);
  private final Config config;

  public Draft(Config config) {
    this.config = config;
  }

  /**
   * 根据组织架构调整 ID 查询发起的流程信息，用户通过『飞书人事-我的团队/人员管理-组织架构』 发起一个组织架构调整会根据 审批流配置发起 一个或多个审批。之后用户可以通过组织架构调整 ID
   * 查询对应的流程ID，以及审批流状态。如需查询单个审批的详情数据，可通过[根据流程 ID
   * 查询组织架构调整记录](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/approval_groups/get)获取。
   *
   * <p>- 用户使用该接口前需提前获取 根据组织架构调整 ID 获取组织架构调整流程信息 权限;-
   * 延迟说明：数据库主从延迟2s以内，即：用户接收到流程状态变更消息后2s内调用此接口可能查询不到数据。 ;
   *
   * <p>官网API文档链接:<a
   * href="https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=get&project=corehr&resource=draft&version=v2">https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=get&project=corehr&resource=draft&version=v2</a>
   * ;
   *
   * <p>使用Demo链接: <a
   * href="https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/corehrv2/GetDraftSample.java">https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/corehrv2/GetDraftSample.java</a>
   * ;
   */
  public GetDraftResp get(GetDraftReq req, RequestOptions reqOptions) throws Exception {
    // 请求参数选项
    if (reqOptions == null) {
      reqOptions = new RequestOptions();
    }

    // 发起请求
    RawResponse httpResponse =
        Transport.send(
            config,
            reqOptions,
            "GET",
            "/open-apis/corehr/v2/drafts/:draft_id",
            Sets.newHashSet(AccessTokenType.Tenant),
            req);

    // 反序列化
    GetDraftResp resp = UnmarshalRespUtil.unmarshalResp(httpResponse, GetDraftResp.class);
    if (resp == null) {
      log.error(
          String.format(
              "%s,callError,req=%s,respHeader=%s,respStatusCode=%s,respBody=%s,",
              "/open-apis/corehr/v2/drafts/:draft_id",
              Jsons.DEFAULT.toJson(req),
              Jsons.DEFAULT.toJson(httpResponse.getHeaders()),
              httpResponse.getStatusCode(),
              new String(httpResponse.getBody(), StandardCharsets.UTF_8)));
      throw new IllegalArgumentException("The result returned by the server is illegal");
    }

    resp.setRawResponse(httpResponse);
    resp.setRequest(req);

    return resp;
  }

  /**
   * 根据组织架构调整 ID 查询发起的流程信息，用户通过『飞书人事-我的团队/人员管理-组织架构』 发起一个组织架构调整会根据 审批流配置发起 一个或多个审批。之后用户可以通过组织架构调整 ID
   * 查询对应的流程ID，以及审批流状态。如需查询单个审批的详情数据，可通过[根据流程 ID
   * 查询组织架构调整记录](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/approval_groups/get)获取。
   *
   * <p>- 用户使用该接口前需提前获取 根据组织架构调整 ID 获取组织架构调整流程信息 权限;-
   * 延迟说明：数据库主从延迟2s以内，即：用户接收到流程状态变更消息后2s内调用此接口可能查询不到数据。 ;
   *
   * <p>官网API文档链接:<a
   * href="https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=get&project=corehr&resource=draft&version=v2">https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=get&project=corehr&resource=draft&version=v2</a>
   * ;
   *
   * <p>使用Demo链接: <a
   * href="https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/corehrv2/GetDraftSample.java">https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/corehrv2/GetDraftSample.java</a>
   * ;
   */
  public GetDraftResp get(GetDraftReq req) throws Exception {
    // 请求参数选项
    RequestOptions reqOptions = new RequestOptions();

    // 发起请求
    RawResponse httpResponse =
        Transport.send(
            config,
            reqOptions,
            "GET",
            "/open-apis/corehr/v2/drafts/:draft_id",
            Sets.newHashSet(AccessTokenType.Tenant),
            req);

    // 反序列化
    GetDraftResp resp = UnmarshalRespUtil.unmarshalResp(httpResponse, GetDraftResp.class);
    if (resp == null) {
      log.error(
          String.format(
              "%s,callError,req=%s,respHeader=%s,respStatusCode=%s,respBody=%s,",
              "/open-apis/corehr/v2/drafts/:draft_id",
              Jsons.DEFAULT.toJson(req),
              Jsons.DEFAULT.toJson(httpResponse.getHeaders()),
              httpResponse.getStatusCode(),
              new String(httpResponse.getBody(), StandardCharsets.UTF_8)));
      throw new IllegalArgumentException("The result returned by the server is illegal");
    }

    resp.setRawResponse(httpResponse);
    resp.setRequest(req);

    return resp;
  }
}
