// Code generated by lark suite oapi sdk gen
/*
 * MIT License
 *
 * Copyright (c) 2022 Lark Technologies Pte. Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice, shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.lark.oapi.service.sheets.v3.model;

import com.google.gson.annotations.SerializedName;
import com.lark.oapi.service.sheets.v3.enums.*;

public class Condition {
  /**
   * 筛选类型，枚举值如下所示。了解更多，参考[筛选指南](https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/sheets-v3/spreadsheet-sheet-filter/filter-user-guide)。;-
   * multiValue ：多值筛选;- number ：数字筛选;- text ：文本筛选;- color ：颜色筛选
   *
   * <p>示例值：number
   */
  @SerializedName("filter_type")
  private String filterType;

  /**
   * 比较类型
   *
   * <p>示例值：less
   */
  @SerializedName("compare_type")
  private String compareType;

  /**
   * 筛选参数
   *
   * <p>示例值：
   */
  @SerializedName("expected")
  private String[] expected;

  public String getFilterType() {
    return this.filterType;
  }

  public void setFilterType(String filterType) {
    this.filterType = filterType;
  }

  public String getCompareType() {
    return this.compareType;
  }

  public void setCompareType(String compareType) {
    this.compareType = compareType;
  }

  public String[] getExpected() {
    return this.expected;
  }

  public void setExpected(String[] expected) {
    this.expected = expected;
  }

  // builder 开始
  public Condition() {}

  public Condition(Builder builder) {
    /**
     * 筛选类型，枚举值如下所示。了解更多，参考[筛选指南](https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/sheets-v3/spreadsheet-sheet-filter/filter-user-guide)。;-
     * multiValue ：多值筛选;- number ：数字筛选;- text ：文本筛选;- color ：颜色筛选
     *
     * <p>示例值：number
     */
    this.filterType = builder.filterType;
    /**
     * 比较类型
     *
     * <p>示例值：less
     */
    this.compareType = builder.compareType;
    /**
     * 筛选参数
     *
     * <p>示例值：
     */
    this.expected = builder.expected;
  }

  public static class Builder {
    /**
     * 筛选类型，枚举值如下所示。了解更多，参考[筛选指南](https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/sheets-v3/spreadsheet-sheet-filter/filter-user-guide)。;-
     * multiValue ：多值筛选;- number ：数字筛选;- text ：文本筛选;- color ：颜色筛选
     *
     * <p>示例值：number
     */
    private String filterType;

    /**
     * 比较类型
     *
     * <p>示例值：less
     */
    private String compareType;

    /**
     * 筛选参数
     *
     * <p>示例值：
     */
    private String[] expected;

    /**
     * 筛选类型，枚举值如下所示。了解更多，参考[筛选指南](https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/sheets-v3/spreadsheet-sheet-filter/filter-user-guide)。;-
     * multiValue ：多值筛选;- number ：数字筛选;- text ：文本筛选;- color ：颜色筛选
     *
     * <p>示例值：number
     *
     * @param filterType
     * @return
     */
    public Builder filterType(String filterType) {
      this.filterType = filterType;
      return this;
    }

    /**
     * 比较类型
     *
     * <p>示例值：less
     *
     * @param compareType
     * @return
     */
    public Builder compareType(String compareType) {
      this.compareType = compareType;
      return this;
    }

    /**
     * 筛选参数
     *
     * <p>示例值：
     *
     * @param expected
     * @return
     */
    public Builder expected(String[] expected) {
      this.expected = expected;
      return this;
    }

    public Condition build() {
      return new Condition(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
