// Code generated by lark suite oapi sdk gen
/*
 * MIT License
 *
 * Copyright (c) 2022 Lark Technologies Pte. Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice, shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.lark.oapi.service.sheets.v3.model;

import com.google.gson.annotations.SerializedName;

public class FilterInfo {

  /**
   * 设置了筛选条件的列
   * <p> 示例值：E
   */
  @SerializedName("col")
  private String col;
  /**
   * 筛选条件
   * <p> 示例值：
   */
  @SerializedName("conditions")
  private Condition[] conditions;

  // builder 开始
  public FilterInfo() {
  }

  public FilterInfo(Builder builder) {
    /**
     * 设置了筛选条件的列
     * <p> 示例值：E
     */
    this.col = builder.col;
    /**
     * 筛选条件
     * <p> 示例值：
     */
    this.conditions = builder.conditions;
  }

  public static Builder newBuilder() {
    return new Builder();
  }

  public String getCol() {
    return this.col;
  }

  public void setCol(String col) {
    this.col = col;
  }

  public Condition[] getConditions() {
    return this.conditions;
  }

  public void setConditions(Condition[] conditions) {
    this.conditions = conditions;
  }

  public static class Builder {

    /**
     * 设置了筛选条件的列
     * <p> 示例值：E
     */
    private String col;
    /**
     * 筛选条件
     * <p> 示例值：
     */
    private Condition[] conditions;

    /**
     * 设置了筛选条件的列
     * <p> 示例值：E
     *
     * @param col
     * @return
     */
    public Builder col(String col) {
      this.col = col;
      return this;
    }


    /**
     * 筛选条件
     * <p> 示例值：
     *
     * @param conditions
     * @return
     */
    public Builder conditions(Condition[] conditions) {
      this.conditions = conditions;
      return this;
    }


    public FilterInfo build() {
      return new FilterInfo(this);
    }
  }
}
