// Code generated by lark suite oapi sdk gen
package com.larksuite.oapi.service.task.v1.model;
import com.larksuite.oapi.service.task.v1.enums.*;
import com.google.gson.annotations.SerializedName;
import com.larksuite.oapi.core.annotation.Body;
import com.larksuite.oapi.core.annotation.Path;
import com.larksuite.oapi.core.annotation.Query;
import java.io.File;
import java.io.ByteArrayOutputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import com.larksuite.oapi.core.utils.Strings;
import com.larksuite.oapi.core.response.BaseResponse;
public class PatchTaskReq {
    @Query
    @SerializedName("user_id_type")
    private String userIdType;
    public String getUserIdType() {
        return this.userIdType;
    }

    public void setUserIdType(String userIdType) {
        this.userIdType = userIdType;
    }

    @Path
    @SerializedName("task_id")
    private String taskId;
    public String getTaskId() {
        return this.taskId;
    }

    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    @Body
    private PatchTaskReqBody body;

    public PatchTaskReqBody getPatchTaskReqBody() {
        return this.body;
    }

    public void setPatchTaskReqBody(PatchTaskReqBody body) {
        this.body = body;
    }

// builder 开始
  public PatchTaskReq(){}

  public PatchTaskReq(Builder builder){
       this.userIdType = builder.userIdType;
       this.taskId = builder.taskId;
        this.body = builder.body;
  }

    public static class Builder {
        private String userIdType;
    
           public Builder userIdType(String userIdType) {
                this.userIdType = userIdType;
                return this;
           }
          public Builder userIdType(com.larksuite.oapi.service.task.v1.enums.UserIdTypeEnum userIdType) {
               this.userIdType = userIdType.getValue();
               return this;
          }
    
        private String taskId;
          public Builder taskId(String taskId) {
               this.taskId = taskId;
               return this;
          }
    
        private PatchTaskReqBody body;
    
        public PatchTaskReqBody getPatchTaskReqBody() {
            return this.body;
        }
        public Builder patchTaskReqBody(PatchTaskReqBody body) {
             this.body = body;
             return this;
        }
    public PatchTaskReq build(){
        return new PatchTaskReq(this);
      }
    }

    public static Builder newBuilder() {
        return new Builder();
    }
}
