// Code generated by lark suite oapi sdk gen
/*
 * MIT License
 *
 * Copyright (c) 2022 Lark Technologies Pte. Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice, shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.lark.oapi.service.im.v2.model;

import com.lark.oapi.core.response.EmptyData;
import com.lark.oapi.service.im.v2.enums.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.SerializedName;
import com.lark.oapi.core.annotation.Body;
import com.lark.oapi.core.annotation.Path;
import com.lark.oapi.core.annotation.Query;

import java.io.ByteArrayOutputStream;
import java.io.FileOutputStream;
import java.io.IOException;

import com.lark.oapi.core.utils.Strings;
import com.lark.oapi.core.response.BaseResponse;

public class OpenDisplayFeedRule {
    /**
     * 主规则
     * <p> 示例值：always_display
     */
    @SerializedName("main_rule")
    private String mainRule;
    /**
     * 重要新消息类型
     * <p> 示例值：
     */
    @SerializedName("msg_types")
    private String[] msgTypes;

    // builder 开始
    public OpenDisplayFeedRule() {
    }

    public OpenDisplayFeedRule(Builder builder) {
        /**
         * 主规则
         * <p> 示例值：always_display
         */
        this.mainRule = builder.mainRule;
        /**
         * 重要新消息类型
         * <p> 示例值：
         */
        this.msgTypes = builder.msgTypes;
    }

    public static Builder newBuilder() {
        return new Builder();
    }

    public String getMainRule() {
        return this.mainRule;
    }

    public void setMainRule(String mainRule) {
        this.mainRule = mainRule;
    }

    public String[] getMsgTypes() {
        return this.msgTypes;
    }

    public void setMsgTypes(String[] msgTypes) {
        this.msgTypes = msgTypes;
    }

    public static class Builder {
        /**
         * 主规则
         * <p> 示例值：always_display
         */
        private String mainRule;
        /**
         * 重要新消息类型
         * <p> 示例值：
         */
        private String[] msgTypes;

        /**
         * 主规则
         * <p> 示例值：always_display
         *
         * @param mainRule
         * @return
         */
        public Builder mainRule(String mainRule) {
            this.mainRule = mainRule;
            return this;
        }

        /**
         * 主规则
         * <p> 示例值：always_display
         *
         * @param mainRule {@link com.lark.oapi.service.im.v2.enums.OpenDisplayFeedRuleMainRuleEnum}
         * @return
         */
        public Builder mainRule(com.lark.oapi.service.im.v2.enums.OpenDisplayFeedRuleMainRuleEnum mainRule) {
            this.mainRule = mainRule.getValue();
            return this;
        }


        /**
         * 重要新消息类型
         * <p> 示例值：
         *
         * @param msgTypes
         * @return
         */
        public Builder msgTypes(String[] msgTypes) {
            this.msgTypes = msgTypes;
            return this;
        }


        public OpenDisplayFeedRule build() {
            return new OpenDisplayFeedRule(this);
        }
    }
}
