// Code generated by lark suite oapi sdk gen
/*
 * MIT License
 *
 * Copyright (c) 2022 Lark Technologies Pte. Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice, shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.lark.oapi.service.performance.v2.model;

import com.google.gson.annotations.SerializedName;
import com.lark.oapi.service.performance.v2.enums.*;

public class QueryMetricTemplateReqBody {
  /**
   * 指标模板 ID 列表，填写时获取指定的指标模版
   *
   * <p>示例值：
   */
  @SerializedName("metrics_template_ids")
  private String[] metricsTemplateIds;

  /**
   * 指标模版状态
   *
   * <p>示例值：to_be_configured
   */
  @SerializedName("status")
  private String status;

  public String[] getMetricsTemplateIds() {
    return this.metricsTemplateIds;
  }

  public void setMetricsTemplateIds(String[] metricsTemplateIds) {
    this.metricsTemplateIds = metricsTemplateIds;
  }

  public String getStatus() {
    return this.status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  // builder 开始
  public QueryMetricTemplateReqBody() {}

  public QueryMetricTemplateReqBody(Builder builder) {
    /**
     * 指标模板 ID 列表，填写时获取指定的指标模版
     *
     * <p>示例值：
     */
    this.metricsTemplateIds = builder.metricsTemplateIds;
    /**
     * 指标模版状态
     *
     * <p>示例值：to_be_configured
     */
    this.status = builder.status;
  }

  public static class Builder {
    /**
     * 指标模板 ID 列表，填写时获取指定的指标模版
     *
     * <p>示例值：
     */
    private String[] metricsTemplateIds;

    /**
     * 指标模版状态
     *
     * <p>示例值：to_be_configured
     */
    private String status;

    /**
     * 指标模板 ID 列表，填写时获取指定的指标模版
     *
     * <p>示例值：
     *
     * @param metricsTemplateIds
     * @return
     */
    public Builder metricsTemplateIds(String[] metricsTemplateIds) {
      this.metricsTemplateIds = metricsTemplateIds;
      return this;
    }

    /**
     * 指标模版状态
     *
     * <p>示例值：to_be_configured
     *
     * @param status
     * @return
     */
    public Builder status(String status) {
      this.status = status;
      return this;
    }

    /**
     * 指标模版状态
     *
     * <p>示例值：to_be_configured
     *
     * @param status {@link
     *     com.lark.oapi.service.performance.v2.enums.QueryMetricTemplateStatusEnum}
     * @return
     */
    public Builder status(
        com.lark.oapi.service.performance.v2.enums.QueryMetricTemplateStatusEnum status) {
      this.status = status.getValue();
      return this;
    }

    public QueryMetricTemplateReqBody build() {
      return new QueryMetricTemplateReqBody(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
