// Code generated by lark suite oapi sdk gen
/*
 * MIT License
 *
 * Copyright (c) 2022 Lark Technologies Pte. Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice, shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.lark.oapi.service.compensation.v1.model;

import com.google.gson.annotations.SerializedName;

public class Indicator {
    /**
     * 薪资统计指标ID
     * <p> 示例值：7196951947228589113
     */
    @SerializedName("id")
    private String id;
    /**
     * 薪资统计指标名称
     * <p> 示例值：年度现金总和
     */
    @SerializedName("name")
    private String name;
    /**
     * 薪资统计指标数值类型
     * <p> 示例值：money
     */
    @SerializedName("value_type")
    private String valueType;
    /**
     * 启用状态
     * <p> 示例值：1
     */
    @SerializedName("active_status")
    private Integer activeStatus;
    /**
     * 多语言名称
     * <p> 示例值：
     */
    @SerializedName("i18n_names")
    private I18nContent[] i18nNames;

    // builder 开始
    public Indicator() {
    }

    public Indicator(Builder builder) {
        /**
         * 薪资统计指标ID
         * <p> 示例值：7196951947228589113
         */
        this.id = builder.id;
        /**
         * 薪资统计指标名称
         * <p> 示例值：年度现金总和
         */
        this.name = builder.name;
        /**
         * 薪资统计指标数值类型
         * <p> 示例值：money
         */
        this.valueType = builder.valueType;
        /**
         * 启用状态
         * <p> 示例值：1
         */
        this.activeStatus = builder.activeStatus;
        /**
         * 多语言名称
         * <p> 示例值：
         */
        this.i18nNames = builder.i18nNames;
    }

    public static Builder newBuilder() {
        return new Builder();
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getValueType() {
        return this.valueType;
    }

    public void setValueType(String valueType) {
        this.valueType = valueType;
    }

    public Integer getActiveStatus() {
        return this.activeStatus;
    }

    public void setActiveStatus(Integer activeStatus) {
        this.activeStatus = activeStatus;
    }

    public I18nContent[] getI18nNames() {
        return this.i18nNames;
    }

    public void setI18nNames(I18nContent[] i18nNames) {
        this.i18nNames = i18nNames;
    }

    public static class Builder {
        /**
         * 薪资统计指标ID
         * <p> 示例值：7196951947228589113
         */
        private String id;
        /**
         * 薪资统计指标名称
         * <p> 示例值：年度现金总和
         */
        private String name;
        /**
         * 薪资统计指标数值类型
         * <p> 示例值：money
         */
        private String valueType;
        /**
         * 启用状态
         * <p> 示例值：1
         */
        private Integer activeStatus;
        /**
         * 多语言名称
         * <p> 示例值：
         */
        private I18nContent[] i18nNames;

        /**
         * 薪资统计指标ID
         * <p> 示例值：7196951947228589113
         *
         * @param id
         * @return
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }


        /**
         * 薪资统计指标名称
         * <p> 示例值：年度现金总和
         *
         * @param name
         * @return
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }


        /**
         * 薪资统计指标数值类型
         * <p> 示例值：money
         *
         * @param valueType
         * @return
         */
        public Builder valueType(String valueType) {
            this.valueType = valueType;
            return this;
        }

        /**
         * 薪资统计指标数值类型
         * <p> 示例值：money
         *
         * @param valueType {@link com.lark.oapi.service.compensation.v1.enums.IndicatorValueTypeEnum}
         * @return
         */
        public Builder valueType(com.lark.oapi.service.compensation.v1.enums.IndicatorValueTypeEnum valueType) {
            this.valueType = valueType.getValue();
            return this;
        }


        /**
         * 启用状态
         * <p> 示例值：1
         *
         * @param activeStatus
         * @return
         */
        public Builder activeStatus(Integer activeStatus) {
            this.activeStatus = activeStatus;
            return this;
        }

        /**
         * 启用状态
         * <p> 示例值：1
         *
         * @param activeStatus {@link com.lark.oapi.service.compensation.v1.enums.IndicatorActiveStatusEnum}
         * @return
         */
        public Builder activeStatus(com.lark.oapi.service.compensation.v1.enums.IndicatorActiveStatusEnum activeStatus) {
            this.activeStatus = activeStatus.getValue();
            return this;
        }


        /**
         * 多语言名称
         * <p> 示例值：
         *
         * @param i18nNames
         * @return
         */
        public Builder i18nNames(I18nContent[] i18nNames) {
            this.i18nNames = i18nNames;
            return this;
        }


        public Indicator build() {
            return new Indicator(this);
        }
    }
}
