// Code generated by lark suite oapi sdk gen
/*
 * MIT License
 *
 * Copyright (c) 2022 Lark Technologies Pte. Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice, shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.lark.oapi.service.compensation.v1.model;

import com.google.gson.annotations.SerializedName;

public class PlanScope {
    /**
     * 是否全部范围
     * <p> 示例值：false
     */
    @SerializedName("is_all")
    private Boolean isAll;
    /**
     * 方案适用范围条件组
     * <p> 示例值：
     */
    @SerializedName("plan_conditions")
    private PlanCondition[] planConditions;

    // builder 开始
    public PlanScope() {
    }

    public PlanScope(Builder builder) {
        /**
         * 是否全部范围
         * <p> 示例值：false
         */
        this.isAll = builder.isAll;
        /**
         * 方案适用范围条件组
         * <p> 示例值：
         */
        this.planConditions = builder.planConditions;
    }

    public static Builder newBuilder() {
        return new Builder();
    }

    public Boolean getIsAll() {
        return this.isAll;
    }

    public void setIsAll(Boolean isAll) {
        this.isAll = isAll;
    }

    public PlanCondition[] getPlanConditions() {
        return this.planConditions;
    }

    public void setPlanConditions(PlanCondition[] planConditions) {
        this.planConditions = planConditions;
    }

    public static class Builder {
        /**
         * 是否全部范围
         * <p> 示例值：false
         */
        private Boolean isAll;
        /**
         * 方案适用范围条件组
         * <p> 示例值：
         */
        private PlanCondition[] planConditions;

        /**
         * 是否全部范围
         * <p> 示例值：false
         *
         * @param isAll
         * @return
         */
        public Builder isAll(Boolean isAll) {
            this.isAll = isAll;
            return this;
        }


        /**
         * 方案适用范围条件组
         * <p> 示例值：
         *
         * @param planConditions
         * @return
         */
        public Builder planConditions(PlanCondition[] planConditions) {
            this.planConditions = planConditions;
            return this;
        }


        public PlanScope build() {
            return new PlanScope(this);
        }
    }
}
