// Code generated by lark suite oapi sdk gen
package com.larksuite.oapi.service.meeting_room.v1.model;
import com.google.gson.annotations.SerializedName;
import com.larksuite.oapi.core.event.model.BaseEventV2;

public class RoomDeletedEvent extends BaseEventV2{
    @SerializedName("event")
    private RoomDeletedEventData event;

    public RoomDeletedEventData getEvent() {
        return this.event;
    }

    public void setEvent(RoomDeletedEventData event) {
        this.event = event;
    }

}
