// Code generated by lark suite oapi sdk gen
package com.larksuite.oapi.service.bitable.v1.model;
import com.larksuite.oapi.service.bitable.v1.enums.*;
import com.google.gson.annotations.SerializedName;
import com.larksuite.oapi.core.annotation.Body;
import com.larksuite.oapi.core.annotation.Path;
import com.larksuite.oapi.core.annotation.Query;
import java.io.File;
import java.io.ByteArrayOutputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import com.larksuite.oapi.core.utils.Strings;
import com.larksuite.oapi.core.response.BaseResponse;
public class CreateAppTableReq {
    @Query
    @SerializedName("user_id_type")
    private String userIdType;
    public String getUserIdType() {
        return this.userIdType;
    }

    public void setUserIdType(String userIdType) {
        this.userIdType = userIdType;
    }

    @Path
    @SerializedName("app_token")
    private String appToken;
    public String getAppToken() {
        return this.appToken;
    }

    public void setAppToken(String appToken) {
        this.appToken = appToken;
    }

    @Body
    private CreateAppTableReqBody body;

    public CreateAppTableReqBody getCreateAppTableReqBody() {
        return this.body;
    }

    public void setCreateAppTableReqBody(CreateAppTableReqBody body) {
        this.body = body;
    }

// builder 开始
  public CreateAppTableReq(){}

  public CreateAppTableReq(Builder builder){
       this.userIdType = builder.userIdType;
       this.appToken = builder.appToken;
        this.body = builder.body;
  }

    public static class Builder {
        private String userIdType;
    
           public Builder userIdType(String userIdType) {
                this.userIdType = userIdType;
                return this;
           }
          public Builder userIdType(com.larksuite.oapi.service.bitable.v1.enums.UserIdTypeEnum userIdType) {
               this.userIdType = userIdType.getValue();
               return this;
          }
    
        private String appToken;
          public Builder appToken(String appToken) {
               this.appToken = appToken;
               return this;
          }
    
        private CreateAppTableReqBody body;
    
        public CreateAppTableReqBody getCreateAppTableReqBody() {
            return this.body;
        }
        public Builder createAppTableReqBody(CreateAppTableReqBody body) {
             this.body = body;
             return this;
        }
    public CreateAppTableReq build(){
        return new CreateAppTableReq(this);
      }
    }

    public static Builder newBuilder() {
        return new Builder();
    }
}
