// Code generated by lark suite oapi sdk gen
package com.larksuite.oapi.service.bitable.v1.model;
import com.larksuite.oapi.service.bitable.v1.enums.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.SerializedName;
import com.larksuite.oapi.core.annotation.Body;
import com.larksuite.oapi.core.annotation.Path;
import com.larksuite.oapi.core.annotation.Query;
import java.io.File;
import java.io.ByteArrayOutputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import com.larksuite.oapi.core.utils.Strings;
import com.larksuite.oapi.core.response.BaseResponse;
public class UpdateAppReqBody {
    @SerializedName("name")
    private String name;
    @SerializedName("is_advanced")
    private Boolean isAdvanced;
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getIsAdvanced() {
        return this.isAdvanced;
    }

    public void setIsAdvanced(Boolean isAdvanced) {
        this.isAdvanced = isAdvanced;
    }


// builder 开始
  public UpdateAppReqBody(){}

  public UpdateAppReqBody(Builder builder){
      this.name = builder.name;
      this.isAdvanced = builder.isAdvanced;
  }

    public static class Builder {
        private String name;
        private Boolean isAdvanced;
        public Builder name(String name) {
             this.name = name;
             return this;
        }
    
        public Builder isAdvanced(Boolean isAdvanced) {
             this.isAdvanced = isAdvanced;
             return this;
        }
    
    
    public UpdateAppReqBody build(){
        return new UpdateAppReqBody(this);
      }
    }

    public static Builder newBuilder() {
        return new Builder();
    }
}
