// Code generated by lark suite oapi sdk gen
/*
 * MIT License
 *
 * Copyright (c) 2022 Lark Technologies Pte. Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice, shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.lark.oapi.service.attendance.v1.model;

import com.google.gson.annotations.SerializedName;
import com.lark.oapi.service.attendance.v1.enums.*;

public class RulemanagerTimeCodeGroupInfo {
  /**
   * 生效日期
   *
   * <p>示例值：2026-04-01
   */
  @SerializedName("efective_date")
  private String efectiveDate;

  /**
   * 失效日期
   *
   * <p>示例值：2026-04-01
   */
  @SerializedName("expire_date")
  private String expireDate;

  /**
   * 出勤类型列表
   *
   * <p>示例值：
   */
  @SerializedName("time_code_infos")
  private RulemanagerTimeCodeInfo[] timeCodeInfos;

  public String getEfectiveDate() {
    return this.efectiveDate;
  }

  public void setEfectiveDate(String efectiveDate) {
    this.efectiveDate = efectiveDate;
  }

  public String getExpireDate() {
    return this.expireDate;
  }

  public void setExpireDate(String expireDate) {
    this.expireDate = expireDate;
  }

  public RulemanagerTimeCodeInfo[] getTimeCodeInfos() {
    return this.timeCodeInfos;
  }

  public void setTimeCodeInfos(RulemanagerTimeCodeInfo[] timeCodeInfos) {
    this.timeCodeInfos = timeCodeInfos;
  }

  // builder 开始
  public RulemanagerTimeCodeGroupInfo() {}

  public RulemanagerTimeCodeGroupInfo(Builder builder) {
    /**
     * 生效日期
     *
     * <p>示例值：2026-04-01
     */
    this.efectiveDate = builder.efectiveDate;
    /**
     * 失效日期
     *
     * <p>示例值：2026-04-01
     */
    this.expireDate = builder.expireDate;
    /**
     * 出勤类型列表
     *
     * <p>示例值：
     */
    this.timeCodeInfos = builder.timeCodeInfos;
  }

  public static class Builder {
    /**
     * 生效日期
     *
     * <p>示例值：2026-04-01
     */
    private String efectiveDate;

    /**
     * 失效日期
     *
     * <p>示例值：2026-04-01
     */
    private String expireDate;

    /**
     * 出勤类型列表
     *
     * <p>示例值：
     */
    private RulemanagerTimeCodeInfo[] timeCodeInfos;

    /**
     * 生效日期
     *
     * <p>示例值：2026-04-01
     *
     * @param efectiveDate
     * @return
     */
    public Builder efectiveDate(String efectiveDate) {
      this.efectiveDate = efectiveDate;
      return this;
    }

    /**
     * 失效日期
     *
     * <p>示例值：2026-04-01
     *
     * @param expireDate
     * @return
     */
    public Builder expireDate(String expireDate) {
      this.expireDate = expireDate;
      return this;
    }

    /**
     * 出勤类型列表
     *
     * <p>示例值：
     *
     * @param timeCodeInfos
     * @return
     */
    public Builder timeCodeInfos(RulemanagerTimeCodeInfo[] timeCodeInfos) {
      this.timeCodeInfos = timeCodeInfos;
      return this;
    }

    public RulemanagerTimeCodeGroupInfo build() {
      return new RulemanagerTimeCodeGroupInfo(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
