// Code generated by lark suite oapi sdk gen
/*
 * MIT License
 *
 * Copyright (c) 2022 Lark Technologies Pte. Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice, shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.lark.oapi.service.attendance.v1.model;

import com.google.gson.annotations.SerializedName;
import com.lark.oapi.service.attendance.v1.enums.*;

public class UserSummaryMetric {
  /**
   * 指标编码
   *
   * <p>示例值：work_day
   */
  @SerializedName("code")
  private String code;

  /**
   * 指标名称
   *
   * <p>示例值：出勤天数
   */
  @SerializedName("name")
  private String name;

  /**
   * 指标值
   *
   * <p>示例值：22
   */
  @SerializedName("value")
  private String value;

  /**
   * 指标单位
   *
   * <p>示例值：天
   */
  @SerializedName("unit")
  private String unit;

  public String getCode() {
    return this.code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getValue() {
    return this.value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public String getUnit() {
    return this.unit;
  }

  public void setUnit(String unit) {
    this.unit = unit;
  }

  // builder 开始
  public UserSummaryMetric() {}

  public UserSummaryMetric(Builder builder) {
    /**
     * 指标编码
     *
     * <p>示例值：work_day
     */
    this.code = builder.code;
    /**
     * 指标名称
     *
     * <p>示例值：出勤天数
     */
    this.name = builder.name;
    /**
     * 指标值
     *
     * <p>示例值：22
     */
    this.value = builder.value;
    /**
     * 指标单位
     *
     * <p>示例值：天
     */
    this.unit = builder.unit;
  }

  public static class Builder {
    /**
     * 指标编码
     *
     * <p>示例值：work_day
     */
    private String code;

    /**
     * 指标名称
     *
     * <p>示例值：出勤天数
     */
    private String name;

    /**
     * 指标值
     *
     * <p>示例值：22
     */
    private String value;

    /**
     * 指标单位
     *
     * <p>示例值：天
     */
    private String unit;

    /**
     * 指标编码
     *
     * <p>示例值：work_day
     *
     * @param code
     * @return
     */
    public Builder code(String code) {
      this.code = code;
      return this;
    }

    /**
     * 指标名称
     *
     * <p>示例值：出勤天数
     *
     * @param name
     * @return
     */
    public Builder name(String name) {
      this.name = name;
      return this;
    }

    /**
     * 指标值
     *
     * <p>示例值：22
     *
     * @param value
     * @return
     */
    public Builder value(String value) {
      this.value = value;
      return this;
    }

    /**
     * 指标单位
     *
     * <p>示例值：天
     *
     * @param unit
     * @return
     */
    public Builder unit(String unit) {
      this.unit = unit;
      return this;
    }

    public UserSummaryMetric build() {
      return new UserSummaryMetric(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
