// Code generated by lark suite oapi sdk gen
package com.larksuite.oapi.service.tenant.v2.model;
import com.google.gson.annotations.SerializedName;

public class Tenant {
    @SerializedName("name")
    private String name;
    @SerializedName("display_id")
    private String displayId;
    @SerializedName("tenant_tag")
    private Integer tenantTag;
    @SerializedName("tenant_key")
    private String tenantKey;
    @SerializedName("avatar")
    private Avatar avatar;

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDisplayId() {
        return this.displayId;
    }

    public void setDisplayId(String displayId) {
        this.displayId = displayId;
    }

    public Integer getTenantTag() {
        return this.tenantTag;
    }

    public void setTenantTag(Integer tenantTag) {
        this.tenantTag = tenantTag;
    }

    public String getTenantKey() {
        return this.tenantKey;
    }

    public void setTenantKey(String tenantKey) {
        this.tenantKey = tenantKey;
    }

    public Avatar getAvatar() {
        return this.avatar;
    }

    public void setAvatar(Avatar avatar) {
        this.avatar = avatar;
    }

}
