// Code generated by lark suite oapi sdk gen
package com.lark.oapi.service.helpdesk.v1.model;

import com.google.gson.annotations.SerializedName;

public class PatchFaqReqBody {

  @SerializedName("faq")
  private FaqUpdateInfo faq;

  // builder 开始
  public PatchFaqReqBody() {
  }

  public PatchFaqReqBody(Builder builder) {
    this.faq = builder.faq;
  }

  public static Builder newBuilder() {
    return new Builder();
  }

  public FaqUpdateInfo getFaq() {
    return this.faq;
  }

  public void setFaq(FaqUpdateInfo faq) {
    this.faq = faq;
  }

  public static class Builder {

    private FaqUpdateInfo faq;

    public Builder faq(FaqUpdateInfo faq) {
      this.faq = faq;
      return this;
    }


    public PatchFaqReqBody build() {
      return new PatchFaqReqBody(this);
    }
  }
}
