// Code generated by lark suite oapi sdk gen
/*
 * MIT License
 *
 * Copyright (c) 2022 Lark Technologies Pte. Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice, shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.lark.oapi.service.directory.v1.resource;

import com.lark.oapi.core.Config;
import com.lark.oapi.core.Transport;
import com.lark.oapi.core.request.RequestOptions;
import com.lark.oapi.core.response.RawResponse;
import com.lark.oapi.core.token.AccessTokenType;
import com.lark.oapi.core.utils.Jsons;
import com.lark.oapi.core.utils.Sets;
import com.lark.oapi.core.utils.UnmarshalRespUtil;
import com.lark.oapi.service.directory.v1.model.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Department {
  private static final Logger log = LoggerFactory.getLogger(Department.class);
  private final Config config;

  public Department(Config config) {
    this.config = config;
  }

  /**
   * 创建部门，本接口用于用于在企业通讯录中创建新部门，支持设置部门名称、父部门、负责人等信息。
   *
   * <p>注意：;- 只能在当前应用的通讯录授权范围内的部门下创建部门，如果要在根部门下创建子部门，必须拥有全员权限。可以在 开发者后台-应用详情-权限管理中 查看通讯录授权范围。;-
   * 本接口中支持的user_access_token
   * 默认为管理员用户，将校验管理员管理范围。当用户有多个管理员身份均可创建部门时，管理员管理范围取最大集。管理员权限可查看帮助中心文档：[管理员创建管理员角色及分配权限](https://www.feishu.cn/hc/zh-CN/articles/360043495213-%E7%AE%A1%E7%90%86%E5%91%98%E5%88%9B%E5%BB%BA%E7%AE%A1%E7%90%86%E5%91%98%E8%A7%92%E8%89%B2%E5%8F%8A%E5%88%86%E9%85%8D%E6%9D%83%E9%99%90#tabs0|lineguid-dU31C);-
   * 拥有本接口权限后，即可写入部门信息。但创建部门后仅返回应用有权限的字段数据，如果需要指定字段请按照文档中的描述申请对应权限。;- 本接口仅对自建应用开放。 ;
   *
   * <p>官网API文档链接:<a
   * href="https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=create&project=directory&resource=department&version=v1">https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=create&project=directory&resource=department&version=v1</a>
   * ;
   *
   * <p>使用Demo链接: <a
   * href="https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/directoryv1/CreateDepartmentSample.java">https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/directoryv1/CreateDepartmentSample.java</a>
   * ;
   */
  public CreateDepartmentResp create(CreateDepartmentReq req, RequestOptions reqOptions)
      throws Exception {
    // 请求参数选项
    if (reqOptions == null) {
      reqOptions = new RequestOptions();
    }

    // 发起请求
    RawResponse httpResponse =
        Transport.send(
            config,
            reqOptions,
            "POST",
            "/open-apis/directory/v1/departments",
            Sets.newHashSet(AccessTokenType.Tenant, AccessTokenType.User),
            req);

    // 反序列化
    CreateDepartmentResp resp =
        UnmarshalRespUtil.unmarshalResp(httpResponse, CreateDepartmentResp.class);
    if (resp == null) {
      log.error(
          String.format(
              "%s,callError,req=%s,respHeader=%s,respStatusCode=%s,respBody=%s,",
              "/open-apis/directory/v1/departments",
              Jsons.DEFAULT.toJson(req),
              Jsons.DEFAULT.toJson(httpResponse.getHeaders()),
              httpResponse.getStatusCode(),
              new String(httpResponse.getBody(), StandardCharsets.UTF_8)));
      throw new IllegalArgumentException("The result returned by the server is illegal");
    }

    resp.setRawResponse(httpResponse);
    resp.setRequest(req);

    return resp;
  }

  /**
   * 创建部门，本接口用于用于在企业通讯录中创建新部门，支持设置部门名称、父部门、负责人等信息。
   *
   * <p>注意：;- 只能在当前应用的通讯录授权范围内的部门下创建部门，如果要在根部门下创建子部门，必须拥有全员权限。可以在 开发者后台-应用详情-权限管理中 查看通讯录授权范围。;-
   * 本接口中支持的user_access_token
   * 默认为管理员用户，将校验管理员管理范围。当用户有多个管理员身份均可创建部门时，管理员管理范围取最大集。管理员权限可查看帮助中心文档：[管理员创建管理员角色及分配权限](https://www.feishu.cn/hc/zh-CN/articles/360043495213-%E7%AE%A1%E7%90%86%E5%91%98%E5%88%9B%E5%BB%BA%E7%AE%A1%E7%90%86%E5%91%98%E8%A7%92%E8%89%B2%E5%8F%8A%E5%88%86%E9%85%8D%E6%9D%83%E9%99%90#tabs0|lineguid-dU31C);-
   * 拥有本接口权限后，即可写入部门信息。但创建部门后仅返回应用有权限的字段数据，如果需要指定字段请按照文档中的描述申请对应权限。;- 本接口仅对自建应用开放。 ;
   *
   * <p>官网API文档链接:<a
   * href="https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=create&project=directory&resource=department&version=v1">https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=create&project=directory&resource=department&version=v1</a>
   * ;
   *
   * <p>使用Demo链接: <a
   * href="https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/directoryv1/CreateDepartmentSample.java">https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/directoryv1/CreateDepartmentSample.java</a>
   * ;
   */
  public CreateDepartmentResp create(CreateDepartmentReq req) throws Exception {
    // 请求参数选项
    RequestOptions reqOptions = new RequestOptions();

    // 发起请求
    RawResponse httpResponse =
        Transport.send(
            config,
            reqOptions,
            "POST",
            "/open-apis/directory/v1/departments",
            Sets.newHashSet(AccessTokenType.Tenant, AccessTokenType.User),
            req);

    // 反序列化
    CreateDepartmentResp resp =
        UnmarshalRespUtil.unmarshalResp(httpResponse, CreateDepartmentResp.class);
    if (resp == null) {
      log.error(
          String.format(
              "%s,callError,req=%s,respHeader=%s,respStatusCode=%s,respBody=%s,",
              "/open-apis/directory/v1/departments",
              Jsons.DEFAULT.toJson(req),
              Jsons.DEFAULT.toJson(httpResponse.getHeaders()),
              httpResponse.getStatusCode(),
              new String(httpResponse.getBody(), StandardCharsets.UTF_8)));
      throw new IllegalArgumentException("The result returned by the server is illegal");
    }

    resp.setRawResponse(httpResponse);
    resp.setRequest(req);

    return resp;
  }

  /**
   * 删除部门，本接口用于删除部门。
   *
   * <p>注意：;-
   * 删除部门需要有待删除部门及其父部门的应用数据权限[配置应用数据权限](https://open.feishu.cn/document/home/introduction-to-scope-and-authorization/configure-app-data-permissions)
   * ;
   *
   * <p>官网API文档链接:<a
   * href="https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=delete&project=directory&resource=department&version=v1">https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=delete&project=directory&resource=department&version=v1</a>
   * ;
   *
   * <p>使用Demo链接: <a
   * href="https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/directoryv1/DeleteDepartmentSample.java">https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/directoryv1/DeleteDepartmentSample.java</a>
   * ;
   */
  public DeleteDepartmentResp delete(DeleteDepartmentReq req, RequestOptions reqOptions)
      throws Exception {
    // 请求参数选项
    if (reqOptions == null) {
      reqOptions = new RequestOptions();
    }

    // 发起请求
    RawResponse httpResponse =
        Transport.send(
            config,
            reqOptions,
            "DELETE",
            "/open-apis/directory/v1/departments/:department_id",
            Sets.newHashSet(AccessTokenType.User, AccessTokenType.Tenant),
            req);

    // 反序列化
    DeleteDepartmentResp resp =
        UnmarshalRespUtil.unmarshalResp(httpResponse, DeleteDepartmentResp.class);
    if (resp == null) {
      log.error(
          String.format(
              "%s,callError,req=%s,respHeader=%s,respStatusCode=%s,respBody=%s,",
              "/open-apis/directory/v1/departments/:department_id",
              Jsons.DEFAULT.toJson(req),
              Jsons.DEFAULT.toJson(httpResponse.getHeaders()),
              httpResponse.getStatusCode(),
              new String(httpResponse.getBody(), StandardCharsets.UTF_8)));
      throw new IllegalArgumentException("The result returned by the server is illegal");
    }

    resp.setRawResponse(httpResponse);
    resp.setRequest(req);

    return resp;
  }

  /**
   * 删除部门，本接口用于删除部门。
   *
   * <p>注意：;-
   * 删除部门需要有待删除部门及其父部门的应用数据权限[配置应用数据权限](https://open.feishu.cn/document/home/introduction-to-scope-and-authorization/configure-app-data-permissions)
   * ;
   *
   * <p>官网API文档链接:<a
   * href="https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=delete&project=directory&resource=department&version=v1">https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=delete&project=directory&resource=department&version=v1</a>
   * ;
   *
   * <p>使用Demo链接: <a
   * href="https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/directoryv1/DeleteDepartmentSample.java">https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/directoryv1/DeleteDepartmentSample.java</a>
   * ;
   */
  public DeleteDepartmentResp delete(DeleteDepartmentReq req) throws Exception {
    // 请求参数选项
    RequestOptions reqOptions = new RequestOptions();

    // 发起请求
    RawResponse httpResponse =
        Transport.send(
            config,
            reqOptions,
            "DELETE",
            "/open-apis/directory/v1/departments/:department_id",
            Sets.newHashSet(AccessTokenType.User, AccessTokenType.Tenant),
            req);

    // 反序列化
    DeleteDepartmentResp resp =
        UnmarshalRespUtil.unmarshalResp(httpResponse, DeleteDepartmentResp.class);
    if (resp == null) {
      log.error(
          String.format(
              "%s,callError,req=%s,respHeader=%s,respStatusCode=%s,respBody=%s,",
              "/open-apis/directory/v1/departments/:department_id",
              Jsons.DEFAULT.toJson(req),
              Jsons.DEFAULT.toJson(httpResponse.getHeaders()),
              httpResponse.getStatusCode(),
              new String(httpResponse.getBody(), StandardCharsets.UTF_8)));
      throw new IllegalArgumentException("The result returned by the server is illegal");
    }

    resp.setRawResponse(httpResponse);
    resp.setRequest(req);

    return resp;
  }

  /**
   * 获取部门列表，本接口用于依据指定条件，批量获取符合条件的部门详情列表。
   *
   * <p>注意：;- 本接口支持tenant_access_token和user_access_token。; -
   * 使用tenant_access_token时，数据权限遵循应用的通讯录权限范围，返回的字段数据为应用有权限的字段。可以在开发者后台-应用详情-权限管理中查看通讯录授权范围。; -
   * 使用user_access_token时，默认为管理员用户，将校验管理员管理范围。当用户有多个管理员身份均可查看部门信息时，管理员管理范围取最大集。管理员权限可查看帮助中心文档：
   * [管理员创建管理员角色及分配权限](https://www.feishu.cn/hc/zh-CN/articles/360043495213-%E7%AE%A1%E7%90%86%E5%91%98%E5%88%9B%E5%BB%BA%E7%AE%A1%E7%90%86%E5%91%98%E8%A7%92%E8%89%B2%E5%8F%8A%E5%88%86%E9%85%8D%E6%9D%83%E9%99%90#tabs0|lineguid-dU31C)
   * ;
   *
   * <p>官网API文档链接:<a
   * href="https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=filter&project=directory&resource=department&version=v1">https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=filter&project=directory&resource=department&version=v1</a>
   * ;
   *
   * <p>使用Demo链接: <a
   * href="https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/directoryv1/FilterDepartmentSample.java">https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/directoryv1/FilterDepartmentSample.java</a>
   * ;
   */
  public FilterDepartmentResp filter(FilterDepartmentReq req, RequestOptions reqOptions)
      throws Exception {
    // 请求参数选项
    if (reqOptions == null) {
      reqOptions = new RequestOptions();
    }

    // 发起请求
    RawResponse httpResponse =
        Transport.send(
            config,
            reqOptions,
            "POST",
            "/open-apis/directory/v1/departments/filter",
            Sets.newHashSet(AccessTokenType.User, AccessTokenType.Tenant),
            req);

    // 反序列化
    FilterDepartmentResp resp =
        UnmarshalRespUtil.unmarshalResp(httpResponse, FilterDepartmentResp.class);
    if (resp == null) {
      log.error(
          String.format(
              "%s,callError,req=%s,respHeader=%s,respStatusCode=%s,respBody=%s,",
              "/open-apis/directory/v1/departments/filter",
              Jsons.DEFAULT.toJson(req),
              Jsons.DEFAULT.toJson(httpResponse.getHeaders()),
              httpResponse.getStatusCode(),
              new String(httpResponse.getBody(), StandardCharsets.UTF_8)));
      throw new IllegalArgumentException("The result returned by the server is illegal");
    }

    resp.setRawResponse(httpResponse);
    resp.setRequest(req);

    return resp;
  }

  /**
   * 获取部门列表，本接口用于依据指定条件，批量获取符合条件的部门详情列表。
   *
   * <p>注意：;- 本接口支持tenant_access_token和user_access_token。; -
   * 使用tenant_access_token时，数据权限遵循应用的通讯录权限范围，返回的字段数据为应用有权限的字段。可以在开发者后台-应用详情-权限管理中查看通讯录授权范围。; -
   * 使用user_access_token时，默认为管理员用户，将校验管理员管理范围。当用户有多个管理员身份均可查看部门信息时，管理员管理范围取最大集。管理员权限可查看帮助中心文档：
   * [管理员创建管理员角色及分配权限](https://www.feishu.cn/hc/zh-CN/articles/360043495213-%E7%AE%A1%E7%90%86%E5%91%98%E5%88%9B%E5%BB%BA%E7%AE%A1%E7%90%86%E5%91%98%E8%A7%92%E8%89%B2%E5%8F%8A%E5%88%86%E9%85%8D%E6%9D%83%E9%99%90#tabs0|lineguid-dU31C)
   * ;
   *
   * <p>官网API文档链接:<a
   * href="https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=filter&project=directory&resource=department&version=v1">https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=filter&project=directory&resource=department&version=v1</a>
   * ;
   *
   * <p>使用Demo链接: <a
   * href="https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/directoryv1/FilterDepartmentSample.java">https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/directoryv1/FilterDepartmentSample.java</a>
   * ;
   */
  public FilterDepartmentResp filter(FilterDepartmentReq req) throws Exception {
    // 请求参数选项
    RequestOptions reqOptions = new RequestOptions();

    // 发起请求
    RawResponse httpResponse =
        Transport.send(
            config,
            reqOptions,
            "POST",
            "/open-apis/directory/v1/departments/filter",
            Sets.newHashSet(AccessTokenType.User, AccessTokenType.Tenant),
            req);

    // 反序列化
    FilterDepartmentResp resp =
        UnmarshalRespUtil.unmarshalResp(httpResponse, FilterDepartmentResp.class);
    if (resp == null) {
      log.error(
          String.format(
              "%s,callError,req=%s,respHeader=%s,respStatusCode=%s,respBody=%s,",
              "/open-apis/directory/v1/departments/filter",
              Jsons.DEFAULT.toJson(req),
              Jsons.DEFAULT.toJson(httpResponse.getHeaders()),
              httpResponse.getStatusCode(),
              new String(httpResponse.getBody(), StandardCharsets.UTF_8)));
      throw new IllegalArgumentException("The result returned by the server is illegal");
    }

    resp.setRawResponse(httpResponse);
    resp.setRequest(req);

    return resp;
  }

  /**
   * 批量获取部门信息，该接口支持传入多个部门ID，返回每个部门的详细信息（如名称、负责人、子部门等）。
   *
   * <p>**注意**：;- 本接口支持tenant_access_token和user_access_token。; -
   * 使用tenant_access_token时，数据权限遵循应用的通讯录权限范围，返回的字段数据为应用有权限的字段。可通过[获取应用通讯录权限范围配置](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/application-v6/application/contacts_range_configuration)确定应用的通讯录权限范围。;
   * - 使用user_access_token时，默认为管理员用户，将校验管理员管理范围。当用户有多个管理员身份均可查看部门信息时，管理员管理范围取最大集。管理员权限可查看帮助中心文档：
   * [管理员创建管理员角色及分配权限](https://www.feishu.cn/hc/zh-CN/articles/360043495213-%E7%AE%A1%E7%90%86%E5%91%98%E5%88%9B%E5%BB%BA%E7%AE%A1%E7%90%86%E5%91%98%E8%A7%92%E8%89%B2%E5%8F%8A%E5%88%86%E9%85%8D%E6%9D%83%E9%99%90#tabs0|lineguid-dU31C);-
   * 为增强飞书组织架构 OpenAPI 的灵活性，于 **2024 年 10 月 21 日**对该 API 接口做出了更新升级，升级内容包括：优化查询已删除部门信息的返回数据结构。; -
   * 升级前，查询已删除部门的信息时，不会返回部门负责人信息；升级后，查询已删除部门的信息时，返回数据中将包括部门负责人信息。 ;
   *
   * <p>官网API文档链接:<a
   * href="https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=mget&project=directory&resource=department&version=v1">https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=mget&project=directory&resource=department&version=v1</a>
   * ;
   *
   * <p>使用Demo链接: <a
   * href="https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/directoryv1/MgetDepartmentSample.java">https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/directoryv1/MgetDepartmentSample.java</a>
   * ;
   */
  public MgetDepartmentResp mget(MgetDepartmentReq req, RequestOptions reqOptions)
      throws Exception {
    // 请求参数选项
    if (reqOptions == null) {
      reqOptions = new RequestOptions();
    }

    // 发起请求
    RawResponse httpResponse =
        Transport.send(
            config,
            reqOptions,
            "POST",
            "/open-apis/directory/v1/departments/mget",
            Sets.newHashSet(AccessTokenType.User, AccessTokenType.Tenant),
            req);

    // 反序列化
    MgetDepartmentResp resp =
        UnmarshalRespUtil.unmarshalResp(httpResponse, MgetDepartmentResp.class);
    if (resp == null) {
      log.error(
          String.format(
              "%s,callError,req=%s,respHeader=%s,respStatusCode=%s,respBody=%s,",
              "/open-apis/directory/v1/departments/mget",
              Jsons.DEFAULT.toJson(req),
              Jsons.DEFAULT.toJson(httpResponse.getHeaders()),
              httpResponse.getStatusCode(),
              new String(httpResponse.getBody(), StandardCharsets.UTF_8)));
      throw new IllegalArgumentException("The result returned by the server is illegal");
    }

    resp.setRawResponse(httpResponse);
    resp.setRequest(req);

    return resp;
  }

  /**
   * 批量获取部门信息，该接口支持传入多个部门ID，返回每个部门的详细信息（如名称、负责人、子部门等）。
   *
   * <p>**注意**：;- 本接口支持tenant_access_token和user_access_token。; -
   * 使用tenant_access_token时，数据权限遵循应用的通讯录权限范围，返回的字段数据为应用有权限的字段。可通过[获取应用通讯录权限范围配置](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/application-v6/application/contacts_range_configuration)确定应用的通讯录权限范围。;
   * - 使用user_access_token时，默认为管理员用户，将校验管理员管理范围。当用户有多个管理员身份均可查看部门信息时，管理员管理范围取最大集。管理员权限可查看帮助中心文档：
   * [管理员创建管理员角色及分配权限](https://www.feishu.cn/hc/zh-CN/articles/360043495213-%E7%AE%A1%E7%90%86%E5%91%98%E5%88%9B%E5%BB%BA%E7%AE%A1%E7%90%86%E5%91%98%E8%A7%92%E8%89%B2%E5%8F%8A%E5%88%86%E9%85%8D%E6%9D%83%E9%99%90#tabs0|lineguid-dU31C);-
   * 为增强飞书组织架构 OpenAPI 的灵活性，于 **2024 年 10 月 21 日**对该 API 接口做出了更新升级，升级内容包括：优化查询已删除部门信息的返回数据结构。; -
   * 升级前，查询已删除部门的信息时，不会返回部门负责人信息；升级后，查询已删除部门的信息时，返回数据中将包括部门负责人信息。 ;
   *
   * <p>官网API文档链接:<a
   * href="https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=mget&project=directory&resource=department&version=v1">https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=mget&project=directory&resource=department&version=v1</a>
   * ;
   *
   * <p>使用Demo链接: <a
   * href="https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/directoryv1/MgetDepartmentSample.java">https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/directoryv1/MgetDepartmentSample.java</a>
   * ;
   */
  public MgetDepartmentResp mget(MgetDepartmentReq req) throws Exception {
    // 请求参数选项
    RequestOptions reqOptions = new RequestOptions();

    // 发起请求
    RawResponse httpResponse =
        Transport.send(
            config,
            reqOptions,
            "POST",
            "/open-apis/directory/v1/departments/mget",
            Sets.newHashSet(AccessTokenType.User, AccessTokenType.Tenant),
            req);

    // 反序列化
    MgetDepartmentResp resp =
        UnmarshalRespUtil.unmarshalResp(httpResponse, MgetDepartmentResp.class);
    if (resp == null) {
      log.error(
          String.format(
              "%s,callError,req=%s,respHeader=%s,respStatusCode=%s,respBody=%s,",
              "/open-apis/directory/v1/departments/mget",
              Jsons.DEFAULT.toJson(req),
              Jsons.DEFAULT.toJson(httpResponse.getHeaders()),
              httpResponse.getStatusCode(),
              new String(httpResponse.getBody(), StandardCharsets.UTF_8)));
      throw new IllegalArgumentException("The result returned by the server is illegal");
    }

    resp.setRawResponse(httpResponse);
    resp.setRequest(req);

    return resp;
  }

  /**
   * 更新部门，本接口用于更新部门信息。仅更新显式传参的部分。
   *
   * <p>官网API文档链接:<a
   * href="https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=patch&project=directory&resource=department&version=v1">https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=patch&project=directory&resource=department&version=v1</a>
   * ;
   *
   * <p>使用Demo链接: <a
   * href="https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/directoryv1/PatchDepartmentSample.java">https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/directoryv1/PatchDepartmentSample.java</a>
   * ;
   */
  public PatchDepartmentResp patch(PatchDepartmentReq req, RequestOptions reqOptions)
      throws Exception {
    // 请求参数选项
    if (reqOptions == null) {
      reqOptions = new RequestOptions();
    }

    // 发起请求
    RawResponse httpResponse =
        Transport.send(
            config,
            reqOptions,
            "PATCH",
            "/open-apis/directory/v1/departments/:department_id",
            Sets.newHashSet(AccessTokenType.User, AccessTokenType.Tenant),
            req);

    // 反序列化
    PatchDepartmentResp resp =
        UnmarshalRespUtil.unmarshalResp(httpResponse, PatchDepartmentResp.class);
    if (resp == null) {
      log.error(
          String.format(
              "%s,callError,req=%s,respHeader=%s,respStatusCode=%s,respBody=%s,",
              "/open-apis/directory/v1/departments/:department_id",
              Jsons.DEFAULT.toJson(req),
              Jsons.DEFAULT.toJson(httpResponse.getHeaders()),
              httpResponse.getStatusCode(),
              new String(httpResponse.getBody(), StandardCharsets.UTF_8)));
      throw new IllegalArgumentException("The result returned by the server is illegal");
    }

    resp.setRawResponse(httpResponse);
    resp.setRequest(req);

    return resp;
  }

  /**
   * 更新部门，本接口用于更新部门信息。仅更新显式传参的部分。
   *
   * <p>官网API文档链接:<a
   * href="https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=patch&project=directory&resource=department&version=v1">https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=patch&project=directory&resource=department&version=v1</a>
   * ;
   *
   * <p>使用Demo链接: <a
   * href="https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/directoryv1/PatchDepartmentSample.java">https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/directoryv1/PatchDepartmentSample.java</a>
   * ;
   */
  public PatchDepartmentResp patch(PatchDepartmentReq req) throws Exception {
    // 请求参数选项
    RequestOptions reqOptions = new RequestOptions();

    // 发起请求
    RawResponse httpResponse =
        Transport.send(
            config,
            reqOptions,
            "PATCH",
            "/open-apis/directory/v1/departments/:department_id",
            Sets.newHashSet(AccessTokenType.User, AccessTokenType.Tenant),
            req);

    // 反序列化
    PatchDepartmentResp resp =
        UnmarshalRespUtil.unmarshalResp(httpResponse, PatchDepartmentResp.class);
    if (resp == null) {
      log.error(
          String.format(
              "%s,callError,req=%s,respHeader=%s,respStatusCode=%s,respBody=%s,",
              "/open-apis/directory/v1/departments/:department_id",
              Jsons.DEFAULT.toJson(req),
              Jsons.DEFAULT.toJson(httpResponse.getHeaders()),
              httpResponse.getStatusCode(),
              new String(httpResponse.getBody(), StandardCharsets.UTF_8)));
      throw new IllegalArgumentException("The result returned by the server is illegal");
    }

    resp.setRawResponse(httpResponse);
    resp.setRequest(req);

    return resp;
  }

  /**
   * 搜索部门，本接口用于搜索部门信息，通过部门名称等关键词搜索部门信息，返回符合条件的部门列表。
   *
   * <p>注意：;- 本接口支持tenant_access_token和user_access_token。; -
   * 使用tenant_access_token时，数据权限遵循应用的通讯录权限范围，返回的字段数据为应用有权限的字段。**考虑到数据安全仅返回最多前100条匹配项**，若需精准结果需要更准确的输入。;
   * - 使用user_access_token时，默认为管理员用户，将校验管理员管理范围。当用户有多个管理员身份均可查看员工信息时，管理员管理范围取最大集。 ;
   *
   * <p>官网API文档链接:<a
   * href="https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=search&project=directory&resource=department&version=v1">https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=search&project=directory&resource=department&version=v1</a>
   * ;
   *
   * <p>使用Demo链接: <a
   * href="https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/directoryv1/SearchDepartmentSample.java">https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/directoryv1/SearchDepartmentSample.java</a>
   * ;
   */
  public SearchDepartmentResp search(SearchDepartmentReq req, RequestOptions reqOptions)
      throws Exception {
    // 请求参数选项
    if (reqOptions == null) {
      reqOptions = new RequestOptions();
    }

    // 发起请求
    RawResponse httpResponse =
        Transport.send(
            config,
            reqOptions,
            "POST",
            "/open-apis/directory/v1/departments/search",
            Sets.newHashSet(AccessTokenType.User, AccessTokenType.Tenant),
            req);

    // 反序列化
    SearchDepartmentResp resp =
        UnmarshalRespUtil.unmarshalResp(httpResponse, SearchDepartmentResp.class);
    if (resp == null) {
      log.error(
          String.format(
              "%s,callError,req=%s,respHeader=%s,respStatusCode=%s,respBody=%s,",
              "/open-apis/directory/v1/departments/search",
              Jsons.DEFAULT.toJson(req),
              Jsons.DEFAULT.toJson(httpResponse.getHeaders()),
              httpResponse.getStatusCode(),
              new String(httpResponse.getBody(), StandardCharsets.UTF_8)));
      throw new IllegalArgumentException("The result returned by the server is illegal");
    }

    resp.setRawResponse(httpResponse);
    resp.setRequest(req);

    return resp;
  }

  /**
   * 搜索部门，本接口用于搜索部门信息，通过部门名称等关键词搜索部门信息，返回符合条件的部门列表。
   *
   * <p>注意：;- 本接口支持tenant_access_token和user_access_token。; -
   * 使用tenant_access_token时，数据权限遵循应用的通讯录权限范围，返回的字段数据为应用有权限的字段。**考虑到数据安全仅返回最多前100条匹配项**，若需精准结果需要更准确的输入。;
   * - 使用user_access_token时，默认为管理员用户，将校验管理员管理范围。当用户有多个管理员身份均可查看员工信息时，管理员管理范围取最大集。 ;
   *
   * <p>官网API文档链接:<a
   * href="https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=search&project=directory&resource=department&version=v1">https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=search&project=directory&resource=department&version=v1</a>
   * ;
   *
   * <p>使用Demo链接: <a
   * href="https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/directoryv1/SearchDepartmentSample.java">https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/directoryv1/SearchDepartmentSample.java</a>
   * ;
   */
  public SearchDepartmentResp search(SearchDepartmentReq req) throws Exception {
    // 请求参数选项
    RequestOptions reqOptions = new RequestOptions();

    // 发起请求
    RawResponse httpResponse =
        Transport.send(
            config,
            reqOptions,
            "POST",
            "/open-apis/directory/v1/departments/search",
            Sets.newHashSet(AccessTokenType.User, AccessTokenType.Tenant),
            req);

    // 反序列化
    SearchDepartmentResp resp =
        UnmarshalRespUtil.unmarshalResp(httpResponse, SearchDepartmentResp.class);
    if (resp == null) {
      log.error(
          String.format(
              "%s,callError,req=%s,respHeader=%s,respStatusCode=%s,respBody=%s,",
              "/open-apis/directory/v1/departments/search",
              Jsons.DEFAULT.toJson(req),
              Jsons.DEFAULT.toJson(httpResponse.getHeaders()),
              httpResponse.getStatusCode(),
              new String(httpResponse.getBody(), StandardCharsets.UTF_8)));
      throw new IllegalArgumentException("The result returned by the server is illegal");
    }

    resp.setRawResponse(httpResponse);
    resp.setRequest(req);

    return resp;
  }
}
