// Code generated by lark suite oapi sdk gen
/*
 * MIT License
 *
 * Copyright (c) 2022 Lark Technologies Pte. Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice, shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.lark.oapi.service.approval.v4.model;

import com.google.gson.annotations.SerializedName;

public class AddSignInstanceReqBody {

  /**
   * <p> 示例值：
   */
  @SerializedName("user_id")
  private String userId;
  /**
   * <p> 示例值：
   */
  @SerializedName("approval_code")
  private String approvalCode;
  /**
   * <p> 示例值：
   */
  @SerializedName("instance_code")
  private String instanceCode;
  /**
   * <p> 示例值：
   */
  @SerializedName("task_id")
  private String taskId;
  /**
   * <p> 示例值：
   */
  @SerializedName("comment")
  private String comment;
  /**
   * <p> 示例值：
   */
  @SerializedName("add_sign_user_ids")
  private String[] addSignUserIds;
  /**
   * <p> 示例值：1
   */
  @SerializedName("add_sign_type")
  private Integer addSignType;
  /**
   * <p> 示例值：1
   */
  @SerializedName("approval_method")
  private Integer approvalMethod;

  // builder 开始
  public AddSignInstanceReqBody() {
  }

  public AddSignInstanceReqBody(Builder builder) {
    /**
     *
     * <p> 示例值：
     */
    this.userId = builder.userId;
    /**
     *
     * <p> 示例值：
     */
    this.approvalCode = builder.approvalCode;
    /**
     *
     * <p> 示例值：
     */
    this.instanceCode = builder.instanceCode;
    /**
     *
     * <p> 示例值：
     */
    this.taskId = builder.taskId;
    /**
     *
     * <p> 示例值：
     */
    this.comment = builder.comment;
    /**
     *
     * <p> 示例值：
     */
    this.addSignUserIds = builder.addSignUserIds;
    /**
     *
     * <p> 示例值：1
     */
    this.addSignType = builder.addSignType;
    /**
     *
     * <p> 示例值：1
     */
    this.approvalMethod = builder.approvalMethod;
  }

  public static Builder newBuilder() {
    return new Builder();
  }

  public String getUserId() {
    return this.userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public String getApprovalCode() {
    return this.approvalCode;
  }

  public void setApprovalCode(String approvalCode) {
    this.approvalCode = approvalCode;
  }

  public String getInstanceCode() {
    return this.instanceCode;
  }

  public void setInstanceCode(String instanceCode) {
    this.instanceCode = instanceCode;
  }

  public String getTaskId() {
    return this.taskId;
  }

  public void setTaskId(String taskId) {
    this.taskId = taskId;
  }

  public String getComment() {
    return this.comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public String[] getAddSignUserIds() {
    return this.addSignUserIds;
  }

  public void setAddSignUserIds(String[] addSignUserIds) {
    this.addSignUserIds = addSignUserIds;
  }

  public Integer getAddSignType() {
    return this.addSignType;
  }

  public void setAddSignType(Integer addSignType) {
    this.addSignType = addSignType;
  }

  public Integer getApprovalMethod() {
    return this.approvalMethod;
  }

  public void setApprovalMethod(Integer approvalMethod) {
    this.approvalMethod = approvalMethod;
  }

  public static class Builder {

    /**
     * <p> 示例值：
     */
    private String userId;
    /**
     * <p> 示例值：
     */
    private String approvalCode;
    /**
     * <p> 示例值：
     */
    private String instanceCode;
    /**
     * <p> 示例值：
     */
    private String taskId;
    /**
     * <p> 示例值：
     */
    private String comment;
    /**
     * <p> 示例值：
     */
    private String[] addSignUserIds;
    /**
     * <p> 示例值：1
     */
    private Integer addSignType;
    /**
     * <p> 示例值：1
     */
    private Integer approvalMethod;

    /**
     * <p> 示例值：
     *
     * @param userId
     * @return
     */
    public Builder userId(String userId) {
      this.userId = userId;
      return this;
    }


    /**
     * <p> 示例值：
     *
     * @param approvalCode
     * @return
     */
    public Builder approvalCode(String approvalCode) {
      this.approvalCode = approvalCode;
      return this;
    }


    /**
     * <p> 示例值：
     *
     * @param instanceCode
     * @return
     */
    public Builder instanceCode(String instanceCode) {
      this.instanceCode = instanceCode;
      return this;
    }


    /**
     * <p> 示例值：
     *
     * @param taskId
     * @return
     */
    public Builder taskId(String taskId) {
      this.taskId = taskId;
      return this;
    }


    /**
     * <p> 示例值：
     *
     * @param comment
     * @return
     */
    public Builder comment(String comment) {
      this.comment = comment;
      return this;
    }


    /**
     * <p> 示例值：
     *
     * @param addSignUserIds
     * @return
     */
    public Builder addSignUserIds(String[] addSignUserIds) {
      this.addSignUserIds = addSignUserIds;
      return this;
    }


    /**
     * <p> 示例值：1
     *
     * @param addSignType
     * @return
     */
    public Builder addSignType(Integer addSignType) {
      this.addSignType = addSignType;
      return this;
    }

    /**
     * <p> 示例值：1
     *
     * @param addSignType {@link com.lark.oapi.service.approval.v4.enums.AddSignInstanceAddSignEnumEnum}
     * @return
     */
    public Builder addSignType(
        com.lark.oapi.service.approval.v4.enums.AddSignInstanceAddSignEnumEnum addSignType) {
      this.addSignType = addSignType.getValue();
      return this;
    }


    /**
     * <p> 示例值：1
     *
     * @param approvalMethod
     * @return
     */
    public Builder approvalMethod(Integer approvalMethod) {
      this.approvalMethod = approvalMethod;
      return this;
    }

    /**
     * <p> 示例值：1
     *
     * @param approvalMethod {@link com.lark.oapi.service.approval.v4.enums.AddSignInstanceApprovalMethodEnumEnum}
     * @return
     */
    public Builder approvalMethod(
        com.lark.oapi.service.approval.v4.enums.AddSignInstanceApprovalMethodEnumEnum approvalMethod) {
      this.approvalMethod = approvalMethod.getValue();
      return this;
    }


    public AddSignInstanceReqBody build() {
      return new AddSignInstanceReqBody(this);
    }
  }
}
