// Code generated by lark suite oapi sdk gen
/*
 * MIT License
 *
 * Copyright (c) 2022 Lark Technologies Pte. Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice, shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.lark.oapi.service.approval.v4.model;

import com.google.gson.annotations.SerializedName;
import com.lark.oapi.service.approval.v4.enums.*;

public class EntityProcessRecord {
  /**
   * 新增的条数
   *
   * <p>示例值：10
   */
  @SerializedName("insert_num")
  private Integer insertNum;

  /**
   * 更新的条数
   *
   * <p>示例值：10
   */
  @SerializedName("update_num")
  private Integer updateNum;

  /**
   * 删除的条数
   *
   * <p>示例值：10
   */
  @SerializedName("delete_num")
  private Integer deleteNum;

  public Integer getInsertNum() {
    return this.insertNum;
  }

  public void setInsertNum(Integer insertNum) {
    this.insertNum = insertNum;
  }

  public Integer getUpdateNum() {
    return this.updateNum;
  }

  public void setUpdateNum(Integer updateNum) {
    this.updateNum = updateNum;
  }

  public Integer getDeleteNum() {
    return this.deleteNum;
  }

  public void setDeleteNum(Integer deleteNum) {
    this.deleteNum = deleteNum;
  }

  // builder 开始
  public EntityProcessRecord() {}

  public EntityProcessRecord(Builder builder) {
    /**
     * 新增的条数
     *
     * <p>示例值：10
     */
    this.insertNum = builder.insertNum;
    /**
     * 更新的条数
     *
     * <p>示例值：10
     */
    this.updateNum = builder.updateNum;
    /**
     * 删除的条数
     *
     * <p>示例值：10
     */
    this.deleteNum = builder.deleteNum;
  }

  public static class Builder {
    /**
     * 新增的条数
     *
     * <p>示例值：10
     */
    private Integer insertNum;

    /**
     * 更新的条数
     *
     * <p>示例值：10
     */
    private Integer updateNum;

    /**
     * 删除的条数
     *
     * <p>示例值：10
     */
    private Integer deleteNum;

    /**
     * 新增的条数
     *
     * <p>示例值：10
     *
     * @param insertNum
     * @return
     */
    public Builder insertNum(Integer insertNum) {
      this.insertNum = insertNum;
      return this;
    }

    /**
     * 更新的条数
     *
     * <p>示例值：10
     *
     * @param updateNum
     * @return
     */
    public Builder updateNum(Integer updateNum) {
      this.updateNum = updateNum;
      return this;
    }

    /**
     * 删除的条数
     *
     * <p>示例值：10
     *
     * @param deleteNum
     * @return
     */
    public Builder deleteNum(Integer deleteNum) {
      this.deleteNum = deleteNum;
      return this;
    }

    public EntityProcessRecord build() {
      return new EntityProcessRecord(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
