// Code generated by lark suite oapi sdk gen
package com.larksuite.oapi.service.wiki.v2.model;

import com.google.gson.annotations.SerializedName;
import com.larksuite.oapi.core.annotation.Body;
import com.larksuite.oapi.core.annotation.Path;

public class CopySpaceNodeReq {
    @Path
    @SerializedName("space_id")
    private Long spaceId;
    @Path
    @SerializedName("node_token")
    private String nodeToken;
    @Body
    private CopySpaceNodeReqBody body;

    // builder 开始
    public CopySpaceNodeReq() {
    }

    public CopySpaceNodeReq(Builder builder) {
        this.spaceId = builder.spaceId;
        this.nodeToken = builder.nodeToken;
        this.body = builder.body;
    }

    public static Builder newBuilder() {
        return new Builder();
    }

    public Long getSpaceId() {
        return this.spaceId;
    }

    public void setSpaceId(Long spaceId) {
        this.spaceId = spaceId;
    }

    public String getNodeToken() {
        return this.nodeToken;
    }

    public void setNodeToken(String nodeToken) {
        this.nodeToken = nodeToken;
    }

    public CopySpaceNodeReqBody getCopySpaceNodeReqBody() {
        return this.body;
    }

    public void setCopySpaceNodeReqBody(CopySpaceNodeReqBody body) {
        this.body = body;
    }

    public static class Builder {

        private Long spaceId;
        private String nodeToken;
        private CopySpaceNodeReqBody body;

        public Builder spaceId(Long spaceId) {
            this.spaceId = spaceId;
            return this;
        }

        public Builder nodeToken(String nodeToken) {
            this.nodeToken = nodeToken;
            return this;
        }

        public CopySpaceNodeReqBody getCopySpaceNodeReqBody() {
            return this.body;
        }

        public Builder copySpaceNodeReqBody(CopySpaceNodeReqBody body) {
            this.body = body;
            return this;
        }

        public CopySpaceNodeReq build() {
            return new CopySpaceNodeReq(this);
        }
    }
}
