// Code generated by lark suite oapi sdk gen
/*
 * MIT License
 *
 * Copyright (c) 2022 Lark Technologies Pte. Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice, shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.lark.oapi.service.okr.v2.model;

import com.google.gson.annotations.SerializedName;
import com.lark.oapi.service.okr.v2.enums.*;

public class ProgressRate {
  /**
   * 进展百分比，保留两位小数
   *
   * <p>示例值：50.21
   */
  @SerializedName("progress_percent")
  private Double progressPercent;

  /**
   * 进展状态
   *
   * <p>示例值：0
   */
  @SerializedName("progress_status")
  private Integer progressStatus;

  public Double getProgressPercent() {
    return this.progressPercent;
  }

  public void setProgressPercent(Double progressPercent) {
    this.progressPercent = progressPercent;
  }

  public Integer getProgressStatus() {
    return this.progressStatus;
  }

  public void setProgressStatus(Integer progressStatus) {
    this.progressStatus = progressStatus;
  }

  // builder 开始
  public ProgressRate() {}

  public ProgressRate(Builder builder) {
    /**
     * 进展百分比，保留两位小数
     *
     * <p>示例值：50.21
     */
    this.progressPercent = builder.progressPercent;
    /**
     * 进展状态
     *
     * <p>示例值：0
     */
    this.progressStatus = builder.progressStatus;
  }

  public static class Builder {
    /**
     * 进展百分比，保留两位小数
     *
     * <p>示例值：50.21
     */
    private Double progressPercent;

    /**
     * 进展状态
     *
     * <p>示例值：0
     */
    private Integer progressStatus;

    /**
     * 进展百分比，保留两位小数
     *
     * <p>示例值：50.21
     *
     * @param progressPercent
     * @return
     */
    public Builder progressPercent(Double progressPercent) {
      this.progressPercent = progressPercent;
      return this;
    }

    /**
     * 进展状态
     *
     * <p>示例值：0
     *
     * @param progressStatus
     * @return
     */
    public Builder progressStatus(Integer progressStatus) {
      this.progressStatus = progressStatus;
      return this;
    }

    /**
     * 进展状态
     *
     * <p>示例值：0
     *
     * @param progressStatus {@link
     *     com.lark.oapi.service.okr.v2.enums.ProgressRateProgressStatusEnum}
     * @return
     */
    public Builder progressStatus(
        com.lark.oapi.service.okr.v2.enums.ProgressRateProgressStatusEnum progressStatus) {
      this.progressStatus = progressStatus.getValue();
      return this;
    }

    public ProgressRate build() {
      return new ProgressRate(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
