// Code generated by lark suite oapi sdk gen
package com.larksuite.oapi.service.im.v1.model;

import com.google.gson.annotations.SerializedName;
import com.larksuite.oapi.core.annotation.Body;
import com.larksuite.oapi.core.annotation.Query;

public class CreateChatReq {
    @Query
    @SerializedName("user_id_type")
    private String userIdType;
    @Query
    @SerializedName("set_bot_manager")
    private Boolean setBotManager;
    @Body
    private CreateChatReqBody body;

    // builder 开始
    public CreateChatReq() {
    }

    public CreateChatReq(Builder builder) {
        this.userIdType = builder.userIdType;
        this.setBotManager = builder.setBotManager;
        this.body = builder.body;
    }

    public static Builder newBuilder() {
        return new Builder();
    }

    public String getUserIdType() {
        return this.userIdType;
    }

    public void setUserIdType(String userIdType) {
        this.userIdType = userIdType;
    }

    public Boolean getSetBotManager() {
        return this.setBotManager;
    }

    public void setSetBotManager(Boolean setBotManager) {
        this.setBotManager = setBotManager;
    }

    public CreateChatReqBody getCreateChatReqBody() {
        return this.body;
    }

    public void setCreateChatReqBody(CreateChatReqBody body) {
        this.body = body;
    }

    public static class Builder {
        private String userIdType;
        private Boolean setBotManager;
        private CreateChatReqBody body;

        public Builder userIdType(String userIdType) {
            this.userIdType = userIdType;
            return this;
        }

        public Builder userIdType(com.larksuite.oapi.service.im.v1.enums.UserIdTypeEnum userIdType) {
            this.userIdType = userIdType.getValue();
            return this;
        }

        public Builder setBotManager(Boolean setBotManager) {
            this.setBotManager = setBotManager;
            return this;
        }

        public CreateChatReqBody getCreateChatReqBody() {
            return this.body;
        }

        public Builder createChatReqBody(CreateChatReqBody body) {
            this.body = body;
            return this;
        }

        public CreateChatReq build() {
            return new CreateChatReq(this);
        }
    }
}
