// Code generated by lark suite oapi sdk gen
package com.larksuite.oapi.service.im.v1.model;
import com.larksuite.oapi.service.im.v1.enums.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.SerializedName;
import com.larksuite.oapi.core.annotation.Body;
import com.larksuite.oapi.core.annotation.Path;
import com.larksuite.oapi.core.annotation.Query;
import java.io.File;
import java.io.ByteArrayOutputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import com.larksuite.oapi.core.utils.Strings;
import com.larksuite.oapi.core.response.BaseResponse;
public class ListModerator {
    @SerializedName("user_id_type")
    private String userIdType;
    @SerializedName("user_id")
    private String userId;
    @SerializedName("tenant_key")
    private String tenantKey;
    public String getUserIdType() {
        return this.userIdType;
    }

    public void setUserIdType(String userIdType) {
        this.userIdType = userIdType;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getTenantKey() {
        return this.tenantKey;
    }

    public void setTenantKey(String tenantKey) {
        this.tenantKey = tenantKey;
    }


// builder 开始
  public ListModerator(){}

  public ListModerator(Builder builder){
      this.userIdType = builder.userIdType;
      this.userId = builder.userId;
      this.tenantKey = builder.tenantKey;
  }

    public static class Builder {
        private String userIdType;
        private String userId;
        private String tenantKey;
        public Builder userIdType(String userIdType) {
             this.userIdType = userIdType;
             return this;
        }
    
        public Builder userId(String userId) {
             this.userId = userId;
             return this;
        }
    
        public Builder tenantKey(String tenantKey) {
             this.tenantKey = tenantKey;
             return this;
        }
    
    
    public ListModerator build(){
        return new ListModerator(this);
      }
    }

    public static Builder newBuilder() {
        return new Builder();
    }
}
