// Code generated by lark suite oapi sdk gen
package com.larksuite.oapi.service.im.v1.model;
import com.larksuite.oapi.service.im.v1.enums.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.SerializedName;
import com.larksuite.oapi.core.annotation.Body;
import com.larksuite.oapi.core.annotation.Path;
import com.larksuite.oapi.core.annotation.Query;
import java.io.File;
import java.io.ByteArrayOutputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import com.larksuite.oapi.core.utils.Strings;
import com.larksuite.oapi.core.response.BaseResponse;
public class PatchMessageReqBody {
    @SerializedName("content")
    private String content;
    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }


// builder 开始
  public PatchMessageReqBody(){}

  public PatchMessageReqBody(Builder builder){
      this.content = builder.content;
  }

    public static class Builder {
        private String content;
        public Builder content(String content) {
             this.content = content;
             return this;
        }
    
    
    public PatchMessageReqBody build(){
        return new PatchMessageReqBody(this);
      }
    }

    public static Builder newBuilder() {
        return new Builder();
    }
}
