// Code generated by lark suite oapi sdk gen
/*
 * MIT License
 *
 * Copyright (c) 2022 Lark Technologies Pte. Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice, shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.lark.oapi.service.contact.v3.resource;

import com.lark.oapi.core.Config;
import com.lark.oapi.core.Transport;
import com.lark.oapi.core.request.RequestOptions;
import com.lark.oapi.core.response.RawResponse;
import com.lark.oapi.core.token.AccessTokenType;
import com.lark.oapi.core.utils.Jsons;
import com.lark.oapi.core.utils.Sets;
import com.lark.oapi.core.utils.UnmarshalRespUtil;
import com.lark.oapi.service.contact.v3.model.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class FunctionalRole {
  private static final Logger log = LoggerFactory.getLogger(FunctionalRole.class);
  private final Config config;

  public FunctionalRole(Config config) {
    this.config = config;
  }

  /**
   * 创建角色，调用该接口创建一个角色。
   *
   * <p>## 使用限制;;同一租户下，角色数量上限为 500。 ;
   *
   * <p>官网API文档链接:<a
   * href="https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=create&project=contact&resource=functional_role&version=v3">https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=create&project=contact&resource=functional_role&version=v3</a>
   * ;
   *
   * <p>使用Demo链接: <a
   * href="https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/contactv3/CreateFunctionalRoleSample.java">https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/contactv3/CreateFunctionalRoleSample.java</a>
   * ;
   */
  public CreateFunctionalRoleResp create(CreateFunctionalRoleReq req, RequestOptions reqOptions)
      throws Exception {
    // 请求参数选项
    if (reqOptions == null) {
      reqOptions = new RequestOptions();
    }

    // 发起请求
    RawResponse httpResponse =
        Transport.send(
            config,
            reqOptions,
            "POST",
            "/open-apis/contact/v3/functional_roles",
            Sets.newHashSet(AccessTokenType.Tenant),
            req);

    // 反序列化
    CreateFunctionalRoleResp resp =
        UnmarshalRespUtil.unmarshalResp(httpResponse, CreateFunctionalRoleResp.class);
    if (resp == null) {
      log.error(
          String.format(
              "%s,callError,req=%s,respHeader=%s,respStatusCode=%s,respBody=%s,",
              "/open-apis/contact/v3/functional_roles",
              Jsons.DEFAULT.toJson(req),
              Jsons.DEFAULT.toJson(httpResponse.getHeaders()),
              httpResponse.getStatusCode(),
              new String(httpResponse.getBody(), StandardCharsets.UTF_8)));
      throw new IllegalArgumentException("The result returned by the server is illegal");
    }

    resp.setRawResponse(httpResponse);
    resp.setRequest(req);

    return resp;
  }

  /**
   * 创建角色，调用该接口创建一个角色。
   *
   * <p>## 使用限制;;同一租户下，角色数量上限为 500。 ;
   *
   * <p>官网API文档链接:<a
   * href="https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=create&project=contact&resource=functional_role&version=v3">https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=create&project=contact&resource=functional_role&version=v3</a>
   * ;
   *
   * <p>使用Demo链接: <a
   * href="https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/contactv3/CreateFunctionalRoleSample.java">https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/contactv3/CreateFunctionalRoleSample.java</a>
   * ;
   */
  public CreateFunctionalRoleResp create(CreateFunctionalRoleReq req) throws Exception {
    // 请求参数选项
    RequestOptions reqOptions = new RequestOptions();

    // 发起请求
    RawResponse httpResponse =
        Transport.send(
            config,
            reqOptions,
            "POST",
            "/open-apis/contact/v3/functional_roles",
            Sets.newHashSet(AccessTokenType.Tenant),
            req);

    // 反序列化
    CreateFunctionalRoleResp resp =
        UnmarshalRespUtil.unmarshalResp(httpResponse, CreateFunctionalRoleResp.class);
    if (resp == null) {
      log.error(
          String.format(
              "%s,callError,req=%s,respHeader=%s,respStatusCode=%s,respBody=%s,",
              "/open-apis/contact/v3/functional_roles",
              Jsons.DEFAULT.toJson(req),
              Jsons.DEFAULT.toJson(httpResponse.getHeaders()),
              httpResponse.getStatusCode(),
              new String(httpResponse.getBody(), StandardCharsets.UTF_8)));
      throw new IllegalArgumentException("The result returned by the server is illegal");
    }

    resp.setRawResponse(httpResponse);
    resp.setRequest(req);

    return resp;
  }

  /**
   * 删除角色，调用该接口删除指定角色。
   *
   * <p>##
   * 注意事项;;角色内如果有成员，则不支持直接删除。你可以调用[查询角色下的所有成员信息](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/contact-v3/functional_role-member/list)接口，查看角色内是否还有成员，如果有，可以调用[删除角色下的成员](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/contact-v3/functional_role-member/batch_delete)接口，将角色成员删除后，再删除角色。
   * ;
   *
   * <p>官网API文档链接:<a
   * href="https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=delete&project=contact&resource=functional_role&version=v3">https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=delete&project=contact&resource=functional_role&version=v3</a>
   * ;
   *
   * <p>使用Demo链接: <a
   * href="https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/contactv3/DeleteFunctionalRoleSample.java">https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/contactv3/DeleteFunctionalRoleSample.java</a>
   * ;
   */
  public DeleteFunctionalRoleResp delete(DeleteFunctionalRoleReq req, RequestOptions reqOptions)
      throws Exception {
    // 请求参数选项
    if (reqOptions == null) {
      reqOptions = new RequestOptions();
    }

    // 发起请求
    RawResponse httpResponse =
        Transport.send(
            config,
            reqOptions,
            "DELETE",
            "/open-apis/contact/v3/functional_roles/:role_id",
            Sets.newHashSet(AccessTokenType.Tenant),
            req);

    // 反序列化
    DeleteFunctionalRoleResp resp =
        UnmarshalRespUtil.unmarshalResp(httpResponse, DeleteFunctionalRoleResp.class);
    if (resp == null) {
      log.error(
          String.format(
              "%s,callError,req=%s,respHeader=%s,respStatusCode=%s,respBody=%s,",
              "/open-apis/contact/v3/functional_roles/:role_id",
              Jsons.DEFAULT.toJson(req),
              Jsons.DEFAULT.toJson(httpResponse.getHeaders()),
              httpResponse.getStatusCode(),
              new String(httpResponse.getBody(), StandardCharsets.UTF_8)));
      throw new IllegalArgumentException("The result returned by the server is illegal");
    }

    resp.setRawResponse(httpResponse);
    resp.setRequest(req);

    return resp;
  }

  /**
   * 删除角色，调用该接口删除指定角色。
   *
   * <p>##
   * 注意事项;;角色内如果有成员，则不支持直接删除。你可以调用[查询角色下的所有成员信息](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/contact-v3/functional_role-member/list)接口，查看角色内是否还有成员，如果有，可以调用[删除角色下的成员](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/contact-v3/functional_role-member/batch_delete)接口，将角色成员删除后，再删除角色。
   * ;
   *
   * <p>官网API文档链接:<a
   * href="https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=delete&project=contact&resource=functional_role&version=v3">https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=delete&project=contact&resource=functional_role&version=v3</a>
   * ;
   *
   * <p>使用Demo链接: <a
   * href="https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/contactv3/DeleteFunctionalRoleSample.java">https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/contactv3/DeleteFunctionalRoleSample.java</a>
   * ;
   */
  public DeleteFunctionalRoleResp delete(DeleteFunctionalRoleReq req) throws Exception {
    // 请求参数选项
    RequestOptions reqOptions = new RequestOptions();

    // 发起请求
    RawResponse httpResponse =
        Transport.send(
            config,
            reqOptions,
            "DELETE",
            "/open-apis/contact/v3/functional_roles/:role_id",
            Sets.newHashSet(AccessTokenType.Tenant),
            req);

    // 反序列化
    DeleteFunctionalRoleResp resp =
        UnmarshalRespUtil.unmarshalResp(httpResponse, DeleteFunctionalRoleResp.class);
    if (resp == null) {
      log.error(
          String.format(
              "%s,callError,req=%s,respHeader=%s,respStatusCode=%s,respBody=%s,",
              "/open-apis/contact/v3/functional_roles/:role_id",
              Jsons.DEFAULT.toJson(req),
              Jsons.DEFAULT.toJson(httpResponse.getHeaders()),
              httpResponse.getStatusCode(),
              new String(httpResponse.getBody(), StandardCharsets.UTF_8)));
      throw new IllegalArgumentException("The result returned by the server is illegal");
    }

    resp.setRawResponse(httpResponse);
    resp.setRequest(req);

    return resp;
  }

  /**
   * 修改角色名称，调用本接口修改指定角色的角色名称。
   *
   * <p>官网API文档链接:<a
   * href="https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=update&project=contact&resource=functional_role&version=v3">https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=update&project=contact&resource=functional_role&version=v3</a>
   * ;
   *
   * <p>使用Demo链接: <a
   * href="https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/contactv3/UpdateFunctionalRoleSample.java">https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/contactv3/UpdateFunctionalRoleSample.java</a>
   * ;
   */
  public UpdateFunctionalRoleResp update(UpdateFunctionalRoleReq req, RequestOptions reqOptions)
      throws Exception {
    // 请求参数选项
    if (reqOptions == null) {
      reqOptions = new RequestOptions();
    }

    // 发起请求
    RawResponse httpResponse =
        Transport.send(
            config,
            reqOptions,
            "PUT",
            "/open-apis/contact/v3/functional_roles/:role_id",
            Sets.newHashSet(AccessTokenType.Tenant),
            req);

    // 反序列化
    UpdateFunctionalRoleResp resp =
        UnmarshalRespUtil.unmarshalResp(httpResponse, UpdateFunctionalRoleResp.class);
    if (resp == null) {
      log.error(
          String.format(
              "%s,callError,req=%s,respHeader=%s,respStatusCode=%s,respBody=%s,",
              "/open-apis/contact/v3/functional_roles/:role_id",
              Jsons.DEFAULT.toJson(req),
              Jsons.DEFAULT.toJson(httpResponse.getHeaders()),
              httpResponse.getStatusCode(),
              new String(httpResponse.getBody(), StandardCharsets.UTF_8)));
      throw new IllegalArgumentException("The result returned by the server is illegal");
    }

    resp.setRawResponse(httpResponse);
    resp.setRequest(req);

    return resp;
  }

  /**
   * 修改角色名称，调用本接口修改指定角色的角色名称。
   *
   * <p>官网API文档链接:<a
   * href="https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=update&project=contact&resource=functional_role&version=v3">https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=update&project=contact&resource=functional_role&version=v3</a>
   * ;
   *
   * <p>使用Demo链接: <a
   * href="https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/contactv3/UpdateFunctionalRoleSample.java">https://github.com/larksuite/oapi-sdk-java/tree/v2_main/sample/src/main/java/com/lark/oapi/sample/apiall/contactv3/UpdateFunctionalRoleSample.java</a>
   * ;
   */
  public UpdateFunctionalRoleResp update(UpdateFunctionalRoleReq req) throws Exception {
    // 请求参数选项
    RequestOptions reqOptions = new RequestOptions();

    // 发起请求
    RawResponse httpResponse =
        Transport.send(
            config,
            reqOptions,
            "PUT",
            "/open-apis/contact/v3/functional_roles/:role_id",
            Sets.newHashSet(AccessTokenType.Tenant),
            req);

    // 反序列化
    UpdateFunctionalRoleResp resp =
        UnmarshalRespUtil.unmarshalResp(httpResponse, UpdateFunctionalRoleResp.class);
    if (resp == null) {
      log.error(
          String.format(
              "%s,callError,req=%s,respHeader=%s,respStatusCode=%s,respBody=%s,",
              "/open-apis/contact/v3/functional_roles/:role_id",
              Jsons.DEFAULT.toJson(req),
              Jsons.DEFAULT.toJson(httpResponse.getHeaders()),
              httpResponse.getStatusCode(),
              new String(httpResponse.getBody(), StandardCharsets.UTF_8)));
      throw new IllegalArgumentException("The result returned by the server is illegal");
    }

    resp.setRawResponse(httpResponse);
    resp.setRequest(req);

    return resp;
  }
}
