// Code generated by lark suite oapi sdk gen
/*
 * MIT License
 *
 * Copyright (c) 2022 Lark Technologies Pte. Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice, shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.lark.oapi.service.directory.v1.model;

import com.google.gson.annotations.SerializedName;
import com.lark.oapi.service.directory.v1.enums.*;

public class CreateGuest {
  /**
   * 姓名
   *
   * <p>示例值：
   */
  @SerializedName("name")
  private UpsertGuestName name;

  /**
   * 手机
   *
   * <p>示例值：+8612345678901
   */
  @SerializedName("mobile")
  private String mobile;

  /**
   * 邮箱
   *
   * <p>示例值：abc@abc.com
   */
  @SerializedName("email")
  private String email;

  /**
   * 头像
   *
   * <p>示例值：asdfaserwerweradsfasdf
   */
  @SerializedName("avatar_key")
  private String avatarKey;

  /**
   * 国家地区
   *
   * <p>示例值：MDCT00000256
   */
  @SerializedName("work_country_or_region")
  private String workCountryOrRegion;

  public UpsertGuestName getName() {
    return this.name;
  }

  public void setName(UpsertGuestName name) {
    this.name = name;
  }

  public String getMobile() {
    return this.mobile;
  }

  public void setMobile(String mobile) {
    this.mobile = mobile;
  }

  public String getEmail() {
    return this.email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public String getAvatarKey() {
    return this.avatarKey;
  }

  public void setAvatarKey(String avatarKey) {
    this.avatarKey = avatarKey;
  }

  public String getWorkCountryOrRegion() {
    return this.workCountryOrRegion;
  }

  public void setWorkCountryOrRegion(String workCountryOrRegion) {
    this.workCountryOrRegion = workCountryOrRegion;
  }

  // builder 开始
  public CreateGuest() {}

  public CreateGuest(Builder builder) {
    /**
     * 姓名
     *
     * <p>示例值：
     */
    this.name = builder.name;
    /**
     * 手机
     *
     * <p>示例值：+8612345678901
     */
    this.mobile = builder.mobile;
    /**
     * 邮箱
     *
     * <p>示例值：abc@abc.com
     */
    this.email = builder.email;
    /**
     * 头像
     *
     * <p>示例值：asdfaserwerweradsfasdf
     */
    this.avatarKey = builder.avatarKey;
    /**
     * 国家地区
     *
     * <p>示例值：MDCT00000256
     */
    this.workCountryOrRegion = builder.workCountryOrRegion;
  }

  public static class Builder {
    /**
     * 姓名
     *
     * <p>示例值：
     */
    private UpsertGuestName name;

    /**
     * 手机
     *
     * <p>示例值：+8612345678901
     */
    private String mobile;

    /**
     * 邮箱
     *
     * <p>示例值：abc@abc.com
     */
    private String email;

    /**
     * 头像
     *
     * <p>示例值：asdfaserwerweradsfasdf
     */
    private String avatarKey;

    /**
     * 国家地区
     *
     * <p>示例值：MDCT00000256
     */
    private String workCountryOrRegion;

    /**
     * 姓名
     *
     * <p>示例值：
     *
     * @param name
     * @return
     */
    public Builder name(UpsertGuestName name) {
      this.name = name;
      return this;
    }

    /**
     * 手机
     *
     * <p>示例值：+8612345678901
     *
     * @param mobile
     * @return
     */
    public Builder mobile(String mobile) {
      this.mobile = mobile;
      return this;
    }

    /**
     * 邮箱
     *
     * <p>示例值：abc@abc.com
     *
     * @param email
     * @return
     */
    public Builder email(String email) {
      this.email = email;
      return this;
    }

    /**
     * 头像
     *
     * <p>示例值：asdfaserwerweradsfasdf
     *
     * @param avatarKey
     * @return
     */
    public Builder avatarKey(String avatarKey) {
      this.avatarKey = avatarKey;
      return this;
    }

    /**
     * 国家地区
     *
     * <p>示例值：MDCT00000256
     *
     * @param workCountryOrRegion
     * @return
     */
    public Builder workCountryOrRegion(String workCountryOrRegion) {
      this.workCountryOrRegion = workCountryOrRegion;
      return this;
    }

    public CreateGuest build() {
      return new CreateGuest(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
