// Code generated by lark suite oapi sdk gen
/*
 * MIT License
 *
 * Copyright (c) 2022 Lark Technologies Pte. Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice, shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.lark.oapi.service.directory.v1.model;

import com.lark.oapi.core.response.EmptyData;
import com.lark.oapi.service.directory.v1.enums.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.SerializedName;
import com.lark.oapi.core.annotation.Body;
import com.lark.oapi.core.annotation.Path;
import com.lark.oapi.core.annotation.Query;

import java.io.ByteArrayOutputStream;
import java.io.FileOutputStream;
import java.io.IOException;

import com.lark.oapi.core.utils.Strings;

import java.util.Map;

import com.lark.oapi.core.response.BaseResponse;

public class I18nText {
    /**
     * 默认值
     * <p> 示例值：张三
     */
    @SerializedName("default_value")
    private String defaultValue;
    /**
     * 国际化值，key为zh_cn, ja_jp, en_us, value为对应的值
     * <p> 示例值：
     */
    @SerializedName("i18n_value")
    private Map<String, String> i18nValue;
    /**
     * 默认语种, 取值包括zh_cn,ja_jp,en_us等
     * <p> 示例值：zh_cn
     */
    @SerializedName("default_locale")
    private String defaultLocale;

    // builder 开始
    public I18nText() {
    }

    public I18nText(Builder builder) {
        /**
         * 默认值
         * <p> 示例值：张三
         */
        this.defaultValue = builder.defaultValue;
        /**
         * 国际化值，key为zh_cn, ja_jp, en_us, value为对应的值
         * <p> 示例值：
         */
        this.i18nValue = builder.i18nValue;
        /**
         * 默认语种, 取值包括zh_cn,ja_jp,en_us等
         * <p> 示例值：zh_cn
         */
        this.defaultLocale = builder.defaultLocale;
    }

    public static Builder newBuilder() {
        return new Builder();
    }

    public String getDefaultValue() {
        return this.defaultValue;
    }

    public void setDefaultValue(String defaultValue) {
        this.defaultValue = defaultValue;
    }

    public Map<String, String> getI18nValue() {
        return this.i18nValue;
    }

    public void setI18nValue(Map<String, String> i18nValue) {
        this.i18nValue = i18nValue;
    }

    public String getDefaultLocale() {
        return this.defaultLocale;
    }

    public void setDefaultLocale(String defaultLocale) {
        this.defaultLocale = defaultLocale;
    }

    public static class Builder {
        /**
         * 默认值
         * <p> 示例值：张三
         */
        private String defaultValue;
        /**
         * 国际化值，key为zh_cn, ja_jp, en_us, value为对应的值
         * <p> 示例值：
         */
        private Map<String, String> i18nValue;
        /**
         * 默认语种, 取值包括zh_cn,ja_jp,en_us等
         * <p> 示例值：zh_cn
         */
        private String defaultLocale;

        /**
         * 默认值
         * <p> 示例值：张三
         *
         * @param defaultValue
         * @return
         */
        public Builder defaultValue(String defaultValue) {
            this.defaultValue = defaultValue;
            return this;
        }


        /**
         * 国际化值，key为zh_cn, ja_jp, en_us, value为对应的值
         * <p> 示例值：
         *
         * @param i18nValue
         * @return
         */
        public Builder i18nValue(Map<String, String> i18nValue) {
            this.i18nValue = i18nValue;
            return this;
        }


        /**
         * 默认语种, 取值包括zh_cn,ja_jp,en_us等
         * <p> 示例值：zh_cn
         *
         * @param defaultLocale
         * @return
         */
        public Builder defaultLocale(String defaultLocale) {
            this.defaultLocale = defaultLocale;
            return this;
        }


        public I18nText build() {
            return new I18nText(this);
        }
    }
}
