// Code generated by lark suite oapi sdk gen
package com.lark.oapi.service.im.v1.model;

import com.google.gson.annotations.SerializedName;
import com.lark.oapi.core.response.BaseResponse;

public class GetChatMembersResp extends BaseResponse {

  @SerializedName("data")
  private GetChatMembersDTO body;

  public GetChatMembersDTO getGetChatMembersDTO() {
    return this.body;
  }

  public void setGetChatMembersDTO(GetChatMembersDTO body) {
    this.body = body;
  }
}
