// Code generated by lark suite oapi sdk gen
/*
 * MIT License
 *
 * Copyright (c) 2022 Lark Technologies Pte. Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice, shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.lark.oapi.service.im.v1.model;

import com.google.gson.annotations.SerializedName;
import com.lark.oapi.service.im.v1.enums.*;

public class UserItem {
  /**
   * 成员 ID（按 member_id_type 返回 open_id/union_id/employee_id；user_id 模式跨租户时省略）
   *
   * <p>示例值：ou_a0553eda9014c201e6969b478895c230
   */
  @SerializedName("member_id")
  private String memberId;

  /**
   * 名字
   *
   * <p>示例值：张三
   */
  @SerializedName("name")
  private String name;

  /**
   * tenant key
   *
   * <p>示例值：2ca8gd5j
   */
  @SerializedName("tenant_key")
  private String tenantKey;

  public String getMemberId() {
    return this.memberId;
  }

  public void setMemberId(String memberId) {
    this.memberId = memberId;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getTenantKey() {
    return this.tenantKey;
  }

  public void setTenantKey(String tenantKey) {
    this.tenantKey = tenantKey;
  }

  // builder 开始
  public UserItem() {}

  public UserItem(Builder builder) {
    /**
     * 成员 ID（按 member_id_type 返回 open_id/union_id/employee_id；user_id 模式跨租户时省略）
     *
     * <p>示例值：ou_a0553eda9014c201e6969b478895c230
     */
    this.memberId = builder.memberId;
    /**
     * 名字
     *
     * <p>示例值：张三
     */
    this.name = builder.name;
    /**
     * tenant key
     *
     * <p>示例值：2ca8gd5j
     */
    this.tenantKey = builder.tenantKey;
  }

  public static class Builder {
    /**
     * 成员 ID（按 member_id_type 返回 open_id/union_id/employee_id；user_id 模式跨租户时省略）
     *
     * <p>示例值：ou_a0553eda9014c201e6969b478895c230
     */
    private String memberId;

    /**
     * 名字
     *
     * <p>示例值：张三
     */
    private String name;

    /**
     * tenant key
     *
     * <p>示例值：2ca8gd5j
     */
    private String tenantKey;

    /**
     * 成员 ID（按 member_id_type 返回 open_id/union_id/employee_id；user_id 模式跨租户时省略）
     *
     * <p>示例值：ou_a0553eda9014c201e6969b478895c230
     *
     * @param memberId
     * @return
     */
    public Builder memberId(String memberId) {
      this.memberId = memberId;
      return this;
    }

    /**
     * 名字
     *
     * <p>示例值：张三
     *
     * @param name
     * @return
     */
    public Builder name(String name) {
      this.name = name;
      return this;
    }

    /**
     * tenant key
     *
     * <p>示例值：2ca8gd5j
     *
     * @param tenantKey
     * @return
     */
    public Builder tenantKey(String tenantKey) {
      this.tenantKey = tenantKey;
      return this;
    }

    public UserItem build() {
      return new UserItem(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
