// Code generated by lark suite oapi sdk gen
/*
 * MIT License
 *
 * Copyright (c) 2022 Lark Technologies Pte. Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice, shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.lark.oapi.service.admin.v1.model;

import com.google.gson.annotations.SerializedName;

public class CreateBadgeImageReqBody {

  @SerializedName("image_file")
  private java.io.File imageFile;
  @SerializedName("image_type")
  private Integer imageType;

  // builder 开始
  public CreateBadgeImageReqBody() {
  }

  public CreateBadgeImageReqBody(Builder builder) {
    this.imageFile = builder.imageFile;
    this.imageType = builder.imageType;
  }

  public static Builder newBuilder() {
    return new Builder();
  }

  public java.io.File getImageFile() {
    return this.imageFile;
  }

  public void setImageFile(java.io.File imageFile) {
    this.imageFile = imageFile;
  }

  public Integer getImageType() {
    return this.imageType;
  }

  public void setImageType(Integer imageType) {
    this.imageType = imageType;
  }

  public static class Builder {

    private java.io.File imageFile;
    private Integer imageType;

    public Builder imageFile(java.io.File imageFile) {
      this.imageFile = imageFile;
      return this;
    }

    public Builder imageType(Integer imageType) {
      this.imageType = imageType;
      return this;
    }

    public Builder imageType(com.lark.oapi.service.admin.v1.enums.ImageTypeEnum imageType) {
      this.imageType = imageType.getValue();
      return this;
    }


    public CreateBadgeImageReqBody build() {
      return new CreateBadgeImageReqBody(this);
    }
  }
}
