// Code generated by lark suite oapi sdk gen
package com.lark.oapi.service.admin.v1.model;

import com.google.gson.annotations.SerializedName;
import com.lark.oapi.core.response.BaseResponse;

public class ListAdminDeptStatResp extends BaseResponse {

  @SerializedName("data")
  private ListAdminDeptStat body;

  public ListAdminDeptStat getListAdminDeptStat() {
    return this.body;
  }

  public void setListAdminDeptStat(ListAdminDeptStat body) {
    this.body = body;
  }
}
