// Code generated by lark suite oapi sdk gen
package com.larksuite.oapi.service.approval.v4.model;
import com.larksuite.oapi.service.approval.v4.enums.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.SerializedName;
import com.larksuite.oapi.core.annotation.Body;
import com.larksuite.oapi.core.annotation.Path;
import com.larksuite.oapi.core.annotation.Query;
import java.io.File;
import java.io.ByteArrayOutputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import com.larksuite.oapi.core.utils.Strings;
import com.larksuite.oapi.core.response.BaseResponse;
public class ApprovalForm {
    @SerializedName("form_content")
    private String formContent;
    public String getFormContent() {
        return this.formContent;
    }

    public void setFormContent(String formContent) {
        this.formContent = formContent;
    }


// builder 开始
  public ApprovalForm(){}

  public ApprovalForm(Builder builder){
      this.formContent = builder.formContent;
  }

    public static class Builder {
        private String formContent;
        public Builder formContent(String formContent) {
             this.formContent = formContent;
             return this;
        }
    
    
    public ApprovalForm build(){
        return new ApprovalForm(this);
      }
    }

    public static Builder newBuilder() {
        return new Builder();
    }
}
