// Code generated by lark suite oapi sdk gen
/*
 * MIT License
 *
 * Copyright (c) 2022 Lark Technologies Pte. Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice, shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.lark.oapi.service.performance.v2.enums;

/** 执行角色 */
public enum TemplateStagePerformRoleEnum {
  REVIEWEE("reviewee"), // 被评估人
  INVITED_REVIEWER("invited_reviewer"), // 360°评估人
  SOLID_LINE_LEADER("solid_line_leader"), // 实线上级
  DOTTED_LINE_LEADER("dotted_line_leader"), // 虚线上级
  SECONDARY_SOLID_LINE_LEADER("secondary_solid_line_leader"), // 第二实线上级
  DIRECT_PROJECT_LEADER("direct_project_leader"), // 项目直属上级
  CUSTOM_REVIEW_ROLE("custom_review_role"), // 自定义评估角色
  METRIC_REVIEWER("metric_reviewer"), // 指标评价人
  ADJUSTER("adjuster"), // 校准人
  APPEAL_HANDLER("appeal_handler"), // 复议处理人
  DATA_SOURCE_ADMIN("data_source_admin"), // 数据源录入人
  ;
  private String value;

  TemplateStagePerformRoleEnum(String value) {
    this.value = value;
  }

  public String getValue() {
    return this.value;
  }
}
