// Code generated by lark suite oapi sdk gen
package com.larksuite.oapi.service.application.v6.model;

import com.google.gson.annotations.SerializedName;

public class WorkplaceWidget {
    @SerializedName("min_lark_version")
    private String minLarkVersion;

    // builder 开始
    public WorkplaceWidget() {
    }

    public WorkplaceWidget(Builder builder) {
        this.minLarkVersion = builder.minLarkVersion;
    }

    public static Builder newBuilder() {
        return new Builder();
    }

    public String getMinLarkVersion() {
        return this.minLarkVersion;
    }

    public void setMinLarkVersion(String minLarkVersion) {
        this.minLarkVersion = minLarkVersion;
    }

    public static class Builder {
        private String minLarkVersion;

        public Builder minLarkVersion(String minLarkVersion) {
            this.minLarkVersion = minLarkVersion;
            return this;
        }


        public WorkplaceWidget build() {
            return new WorkplaceWidget(this);
        }
    }
}
